import { deck } from '../types';

export const aeroDeck = deck(
  {
    id: 'aero',
    subject: 'aero',
    title: 'Aerodynamics',
    description:
      'Lift, stalls, load factor, stability, turns — the physics your hands will eventually know.',
  },
  [
    {
      slug: 'four-forces',
      front: 'The four forces, and their relationship in steady straight-and-level flight?',
      back: 'Lift, weight, thrust, drag — in unaccelerated flight they are in equilibrium: lift = weight, thrust = drag.',
      why: 'Equilibrium holds in any unaccelerated flight, including steady climbs and descents — a favorite exam trap.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'aoa',
      front: 'Definition of **angle of attack**?',
      back: 'The angle between the wing chord line and the relative wind.',
      why: 'Not the angle to the horizon. You can stall pointed straight down if you yank hard enough.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'critical-aoa',
      front: 'When does a wing **stall**, always and only?',
      back: 'When it exceeds its critical angle of attack — at any airspeed, any attitude, any power setting.',
      why: 'The critical AOA never changes (~15–18°). The airSPEED at which you reach it changes with weight, load factor, bank, and configuration.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'load-factor-stall',
      front: 'How does **load factor** change stall speed?',
      back: 'Stall speed rises with the square root of load factor: Vs × √n. At 2 g, stall speed is ~41% higher.',
      why: 'A 60° level turn = 2 g. A 50-kt stall becomes 71 kt. This is how base-to-final accidents happen at “safe” speeds.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'bank-load',
      front: 'Load factor in a level **60° bank** turn?',
      back: '2 g — regardless of airspeed or aircraft type.',
      why: '45° is 1.41 g; load factor depends only on bank angle in a level turn.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'va',
      front: 'What is **maneuvering speed (Va)**, and which way does it move with weight?',
      back: 'The speed at or below which full, abrupt control input won’t overstress the airframe (the wing stalls first). It DECREASES as weight decreases.',
      why: 'Lighter airplane = lower AOA in cruise = more AOA in reserve before stall = more g available to hurt you. Slow down more when light in turbulence.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'adverse-yaw',
      front: 'Why does the nose yaw AWAY from the direction you roll — and the fix?',
      back: 'Adverse yaw: the rising wing’s aileron creates more induced drag. Fix: coordinated rudder into the turn.',
      cite: 'PHAK Ch. 6',
    },
    {
      slug: 'left-turning',
      front: 'The four **left-turning tendencies**, and when are they strongest?',
      back: 'Torque, P-factor, spiraling slipstream, gyroscopic precession — strongest at high power and high angle of attack (takeoff and climb).',
      why: 'That’s the right rudder your instructor keeps asking for on every takeoff.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'p-factor',
      front: 'What causes **P-factor**?',
      back: 'At high AOA the descending (right) propeller blade takes a bigger bite (higher AOA and relative speed) than the ascending blade — thrust is offset right of center, yawing left.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'ground-effect',
      front: '**Ground effect**: what changes within a wingspan of the surface?',
      back: 'Reduced induced drag (downwash and wingtip vortices are constrained) — the plane floats on landing and can lift off before it can really climb.',
      why: 'Trap on both ends: floating past your touchdown point, and staggering off a soft field unable to climb out of it.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'induced-parasite',
      front: '**Induced** vs **parasite** drag — which grows with speed?',
      back: 'Parasite grows with speed squared; induced (a byproduct of lift) DECREASES with speed. Their sum is minimum at best glide/best L/D.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'stability-static',
      front: '**Static** vs **dynamic** stability?',
      back: 'Static: the initial tendency after a disturbance (return / stay / diverge). Dynamic: what the oscillations do over time (damp / persist / grow).',
      why: 'Trainers are positively stable both ways — let go and they mostly fix themselves.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'cg-aft',
      front: 'Flying with CG at (or behind) the **aft limit** — handling effects?',
      back: 'Less longitudinal stability, lighter pitch forces, lower stall speed and better cruise — but stall/spin recovery may be difficult or IMPOSSIBLE.',
      why: 'The tail normally pushes down; aft CG reduces that download and the self-correcting nose drop in a stall.',
      cite: 'PHAK Ch. 5, 10',
    },
    {
      slug: 'cg-fwd',
      front: 'Effects of a **forward** CG?',
      back: 'More stable, heavier pitch forces, HIGHER stall speed (more tail-down force = effectively more weight), reduced cruise performance, possibly not enough elevator to flare.',
      cite: 'PHAK Ch. 5, 10',
    },
    {
      slug: 'spin',
      front: 'What must happen for a **spin**, and the standard recovery?',
      back: 'A stall with yaw (one wing deeper into the stall). Recovery: **PARE** — Power idle, Ailerons neutral, Rudder full opposite the rotation, Elevator forward to break the stall; recover from the dive.',
      why: 'No stall, no spin — ever. Coordination in slow flight is spin-proofing.',
      cite: 'PHAK Ch. 5; AFH Ch. 5',
    },
    {
      slug: 'skid-slip',
      front: '**Skidding** vs **slipping** turn — and which one kills on base-to-final?',
      back: 'Skid: too much rudder for the bank — ball thrown to the OUTSIDE of the turn. Slip: too much bank for the rudder — ball falls to the INSIDE. The SKID is the killer: stalled in a skid, the inside wing drops and you spin toward the ground.',
      why: 'Overshooting final and “helping” the turn with inside rudder is the classic setup. Go around instead.',
      cite: 'AFH Ch. 4',
    },
    {
      slug: 'vx-vy',
      front: '**Vx** vs **Vy** — definitions, and what happens to them with altitude?',
      back: 'Vx: best ANGLE of climb (most altitude per distance — obstacles). Vy: best RATE (most altitude per time). With altitude Vx increases and Vy decreases until they meet at the absolute ceiling.',
      cite: 'PHAK Ch. 11',
    },
    {
      slug: 'best-glide',
      front: 'What does **best glide speed** give you, and what ruins the glide?',
      back: 'Maximum distance per altitude lost (best L/D). Ruined by: wind (headwind shortens), flaps/gear, prop windmilling, and chasing the nose above/below the speed.',
      why: 'Engine failure drill: pitch for best glide FIRST, then pick the field.',
      cite: 'PHAK Ch. 5; AFH',
    },
    {
      slug: 'flaps-do',
      front: 'What do **flaps** actually change?',
      back: 'They increase wing camber (and sometimes area): more lift AND more drag at a given AOA — allowing a steeper approach at a lower speed without accelerating.',
      cite: 'PHAK Ch. 6',
    },
    {
      slug: 'frost-aero',
      front: 'Aerodynamic effect of frost/ice/snow on the wing?',
      back: 'Roughness trips the boundary layer: lift is reduced, drag increased, stall AOA is reached earlier — takeoff may be impossible even with “just frost.”',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'turn-rate-radius',
      front: 'For a given bank angle, what do rate and radius of turn do as **speed increases**?',
      back: 'Rate decreases, radius increases. To tighten a turn: slow down and/or bank more.',
      why: 'Canyon-turn logic, and why pattern speeds keep the pattern tidy.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'overbanking',
      front: 'In a steep turn the bank keeps wanting to increase — why?',
      back: 'Overbanking tendency: the outside wing travels faster than the inside wing, generating more lift — hold opposite aileron.',
      cite: 'PHAK Ch. 5; AFH Ch. 9',
    },
    {
      slug: 'lift-eq-levers',
      front: 'In level flight you slow from 110 to 70 knots. To keep lift equal to weight you must…?',
      back: 'Increase angle of attack — lift depends on both speed and AOA; less of one needs more of the other.',
      why: 'This is the whole lift equation without the algebra: L = ½ρV²·S·CL.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'region-reverse',
      front: 'The **region of reversed command** — what’s reversed?',
      back: 'Behind the power curve (slower than max-endurance speed), flying SLOWER requires MORE power. Short-field approaches live near this region.',
      why: 'Low, slow, and dragging it in: adding nose-up without power makes you sink faster.',
      cite: 'PHAK Ch. 11; AFH',
    },
    {
      slug: 'wake-vortices',
      front: 'Where are **wingtip vortices** worst, and how do they move?',
      back: 'Behind a HEAVY, CLEAN, SLOW aircraft. They sink 400–500 fpm, level off ~900 ft below the flight path, and drift with the wind.',
      why: 'A light crosswind is the trap — it can hold the upwind vortex ON the runway. Land beyond a jet’s touchdown point; rotate before its rotation point.',
      cite: 'AIM 7-4-4 (wake turbulence)',
      unverified: true,
    },
    {
      slug: 'stall-recovery',
      front: 'The universal first action in ANY stall recovery?',
      back: 'Reduce the angle of attack — pitch forward. Then power, then level wings with coordinated controls.',
      why: 'Pulling harder because the ground is coming is the fatal instinct this training exists to overwrite.',
      cite: 'AFH Ch. 5',
    },
    {
      slug: 'axes-controls',
      front: 'The three axes, the motion around each, and the control that commands it?',
      back: 'Longitudinal (nose-to-tail): roll — ailerons. Lateral (wingtip-to-wingtip): pitch — elevator. Vertical: yaw — rudder.',
      why: 'All three axes cross at the center of gravity.',
      cite: 'PHAK Ch. 6',
    },
    {
      slug: 'load-formula',
      front: 'Load factor in a level turn as a function of bank?',
      back: 'n = 1 / cos(bank). 30° → 1.15 g · 45° → 1.41 g · 60° → 2.0 g · 75° → 3.9 g.',
      why: 'It grows slowly then explosively — the last 15° of bank cost more than the first 60.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'flap-types',
      front: 'Four flap types, in rough order of effectiveness?',
      back: 'Plain (simple hinge) → split (bottom surface only, lots of drag) → slotted (energizes airflow — most trainers) → Fowler (slides aft, adds area AND camber — most effective).',
      cite: 'PHAK Ch. 6',
    },
    {
      slug: 'dihedral',
      front: 'What does **dihedral** (upward wing angle) give the airplane?',
      back: 'Lateral (roll) stability: in a sideslip the lower wing meets the relative wind at higher AOA, generating a rolling moment back toward level.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'washout',
      front: 'Why are wingtips often twisted to a lower angle of incidence (**washout**)?',
      back: 'So the root stalls before the tip — ailerons keep working into the stall, and the nose drops straight instead of a wing snapping over.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'chord-camber',
      front: 'Define **chord line** and **camber**.',
      back: 'Chord: straight line from leading to trailing edge. Camber: the curvature of the wing surfaces relative to the chord — more camber, more lift (and drag) at a given AOA.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'angle-incidence',
      front: '**Angle of incidence** vs angle of attack?',
      back: 'Incidence: the fixed angle between the wing chord and the fuselage reference line — set by the factory, not the pilot. AOA: chord vs relative wind — yours to control.',
      cite: 'PHAK Ch. 5',
    },
    {
      slug: 'stabilator-trim',
      front: 'What does **trim** actually do?',
      back: 'Holds a control surface deflection (or stabilator position) so YOU don’t have to hold the force — trim for a speed/attitude, then the airplane maintains it hands-light.',
      why: '“Pitch, power, trim” — trim off the pressure, never fly the trim.',
      cite: 'PHAK Ch. 6; AFH',
    },
    {
      slug: 'diff-ailerons',
      front: 'How do **differential/Frise ailerons** fight adverse yaw?',
      back: 'Differential: the up-going aileron deflects more than the down-going one. Frise: the raised aileron’s nose pokes into the airstream. Both add drag on the DOWN-going wing side to balance the yaw.',
      cite: 'PHAK Ch. 6',
    },
    {
      slug: 'stall-strips',
      front: 'Those small metal wedges on the inboard leading edge — what do they do?',
      back: 'Stall strips force the wing root to stall first at high AOA, preserving aileron control and giving buffet warning.',
      cite: 'PHAK Ch. 5',
      unverified: true,
    },
    {
      slug: 'power-on-off-stall',
      front: '**Power-on** vs **power-off** stalls — what does each rehearse?',
      back: 'Power-off (approach configuration): the base/final stall. Power-on (takeoff configuration, high pitch): the departure stall. Same aerodynamics, different left-turning forces and nose attitudes.',
      cite: 'AFH Ch. 5',
    },
    {
      slug: 'best-glide-weight',
      front: 'Does best glide SPEED change with weight? Does glide RANGE?',
      back: 'Best glide speed decreases at lighter weight; the glide RATIO (range per altitude) stays essentially the same — you just fly it slower.',
      cite: 'PHAK Ch. 5, 11',
    },
  ],
);
