import { deck } from '../types';

/*
 * Navigation & cross-country planning: pilotage, dead reckoning, VOR work,
 * the wind triangle, and fuel math. Heavily tested, and the core of the
 * 150 NM solo cross-country.
 */

export const navDeck = deck(
  {
    id: 'nav',
    subject: 'nav',
    title: 'Navigation & flight planning',
    description:
      'Pilotage, dead reckoning, VOR, wind triangle, and the arithmetic of getting there with fuel left.',
  },
  [
    {
      slug: 'pilotage-dr',
      front: '**Pilotage** vs **dead reckoning** — define both.',
      back: 'Pilotage: navigating by visible landmarks against the chart. Dead reckoning: computing position from heading, speed, wind, and time.',
      why: 'Real VFR navigation is both at once: DR predicts, pilotage confirms. GPS is a bonus, not a plan.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'course-heading-track',
      front: 'Distinguish **course**, **heading**, and **track**.',
      back: 'Course: intended path over the ground. Heading: where the nose points. Track: actual path over the ground.',
      why: 'Wind is the gap between them — heading = course corrected for wind; track is what actually happened.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'tc-to-ch',
      front: 'The chain from **true course** to **compass heading**?',
      back: 'True course ± wind correction angle = true heading; ± variation = magnetic heading; ± deviation = compass heading.',
      why: 'Mnemonic: **TVMDC** — “True Virgins Make Dull Company.” East is least (subtract), west is best (add).',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'wca',
      front: 'What is the **wind correction angle**?',
      back: 'The angle between course and heading needed to keep the track on the course despite crosswind — nose into the wind.',
      why: 'A direct crosswind at half your TAS needs roughly a 30° correction; typical corrections are single digits to ~15°.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'gs-tas',
      front: '**Groundspeed** vs **true airspeed** — what moves it?',
      back: 'GS = TAS adjusted for the wind component along your track: headwind subtracts, tailwind adds.',
      why: '110 TAS into a 20-kt headwind = 90 GS — a 150 NM leg takes 100 minutes, not 82. Fuel plans live on GS.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'nm-min',
      front: 'Quick math: at **120 knots** groundspeed, how far do you go per minute?',
      back: '2 NM per minute (60 kt = 1 NM/min; 90 kt = 1.5; 120 kt = 2).',
      why: 'The “speed ÷ 60” trick does most checkpoint timing in your head.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'fuel-calc',
      front: 'Burn rate 8.5 GPH, groundspeed 100 kt. Fuel for a 150 NM leg?',
      back: '150/100 = 1.5 hr → 1.5 × 8.5 ≈ 12.8 gallons.',
      why: 'Time first, then fuel. Then add reserve (30/45 min legal, 1 hr smart) before deciding it fits.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'checkpoints',
      front: 'What makes a **good visual checkpoint**?',
      back: 'Big, unique, and hard to mistake: river bends, highway junctions, towns with distinctive shapes, lakes — ideally a combination.',
      why: 'A “water tower” is a bad checkpoint; every town has one. Puget Sound shorelines are gifts.',
      cite: 'PHAK Ch. 16; AFH',
    },
    {
      slug: 'vor-what',
      front: 'What does a **VOR** transmit, and what does your receiver show?',
      back: '360 radials outward from the station (magnetic). The CDI shows your position relative to the selected radial — regardless of your heading.',
      why: 'The needle doesn’t know where the nose points. That’s its power and its trap.',
      cite: 'PHAK Ch. 16; AIM 1-1-3',
    },
    {
      slug: 'vor-cdi',
      front: 'OBS set 090, TO flag showing, needle centered. Where are you?',
      back: 'On the 270 radial (west of the station), and flying 090 would take you TO it.',
      why: 'TO means the OBS course points at the station from your side. The radial you sit on is the reciprocal of the TO course.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'vor-reverse',
      front: 'When does a VOR give **reverse sensing**?',
      back: 'When the OBS is set roughly opposite the course you actually fly (heading TO with a FROM setting or vice versa) — the needle moves the wrong way.',
      why: 'Cure: set the OBS to (roughly) your heading; then the needle points at the course. VORs never truly reverse — setups do.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'vor-ident',
      front: 'Before using a VOR you must —',
      back: 'Identify it by its Morse code (or voice) ident. No ident = station unusable (maintenance strips the ident).',
      cite: 'AIM 1-1-3',
    },
    {
      slug: 'vor-check',
      front: 'Ways to check VOR accuracy (VFR good practice, IFR required)?',
      back: 'VOT test facility (±4°: set 360, FROM / 180, TO), designated ground checkpoint (±4°), airborne checkpoint (±6°), dual VOR cross-check (4° between them).',
      why: '“Cessna 182” memory hook: 360 FROM / 180 TO on a VOT.',
      cite: '14 CFR 91.171; AIM 1-1-4',
    },
    {
      slug: 'vor-cone',
      front: 'Passing directly over a VOR, the needle swings wildly. Why?',
      back: 'The cone of confusion — the zone above the station where radials converge. Station passage = TO/FROM flip; just hold heading through it.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'radial-position',
      front: 'You’re southwest of a VOR. Which radial are you on?',
      back: 'The 225 radial (radials radiate outward: your bearing FROM the station).',
      why: 'Position is always a radial + distance. “On the 225 at 15 DME” fixes you exactly.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'gps-raim',
      front: 'What does a handheld/panel **GPS** not guarantee that certified IFR GPS monitors?',
      back: 'Integrity — RAIM (receiver autonomous integrity monitoring) warns when satellite geometry can’t be trusted. VFR GPS: cross-check with chart and clock.',
      cite: 'AIM 1-1-17',
      unverified: true,
    },
    {
      slug: 'latlong',
      front: 'How do **latitude** and **longitude** lines run, and which is which on the chart edge?',
      back: 'Latitude: parallel east-west lines measuring north-south position (0° equator). Longitude: north-south meridians measuring east-west (0° Greenwich). One minute of latitude ≈ 1 NM.',
      why: 'Puget Sound sits near N47° W122°. The 1-minute-of-latitude = 1 NM trick turns the chart border into a ruler.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'magnetic-dip',
      front: 'Why prefer a heading indicator over the compass in turns?',
      back: 'Magnetic dip drags the compass into turning/acceleration errors (UNOS/ANDS); the gyro heading indicator has no dip errors — but drifts and needs resetting to the compass in level flight.',
      cite: 'PHAK Ch. 8, 16',
    },
    {
      slug: 'isogonic-apply',
      front: 'True course 250°, variation 15°E, WCA 5° right. Magnetic heading?',
      back: '250 + 5 = 255 true heading; 255 − 15 = **240° magnetic**.',
      why: 'Order matters: wind first (true), then variation, then deviation.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'toc',
      front: 'Why compute a **top-of-climb** point in planning?',
      back: 'Climb burns more fuel and covers less ground per minute than cruise — planning the whole leg at cruise numbers understates time and fuel.',
      why: 'POH gives “time, fuel, distance to climb” tables; the first checkpoint often lands near TOC.',
      cite: 'PHAK Ch. 16; POH Section 5',
    },
    {
      slug: 'diversion',
      front: 'In-flight **diversion**: the quick method?',
      back: 'Turn roughly toward the alternate first, then refine: estimate course with the chart (thumb/plotter), distance in ~10 NM steps, time from groundspeed, fuel from time.',
      why: 'Checkride staple. Fly the airplane, divert approximately, refine en route.',
      cite: 'AFH; PHAK Ch. 16',
    },
    {
      slug: 'lost',
      front: 'You’re lost. The **four Cs**?',
      back: 'Climb (see farther, better reception), Communicate (121.5, FSS, ATC — confess), Comply (with instructions), Conserve (lean, slow to endurance speed).',
      why: 'Nobody has ever been violated for confessing lost. Plenty have died avoiding the embarrassment.',
      cite: 'AFH Ch. 16',
      unverified: true,
    },
    {
      slug: 'vfr-flightplan',
      front: 'What does a **VFR flight plan** actually do, and what must you remember?',
      back: 'It triggers search and rescue if you don’t close it — nothing else. Open it after departure, CLOSE it after landing (FSS), or SAR launches looking for you.',
      why: '30 minutes after your ETA, the phone calls start. Flight following is separate: radar advisories, no SAR trigger.',
      cite: 'AIM 5-1-4, 5-1-14',
    },
    {
      slug: 'flight-following',
      front: 'What is **VFR flight following**, and what does it not do?',
      back: 'Radar traffic advisories from ATC, workload permitting. It does not relieve see-and-avoid, guarantee service, or replace a flight plan’s SAR function.',
      why: 'Ask for it: “Seattle Approach, Skyhawk 731TW, VFR request.” Free safety net over the Sound.',
      cite: 'AIM 4-1-15',
    },
    {
      slug: 'cruise-alt-pick',
      front: 'Choosing a VFR cruise altitude: what four things constrain it?',
      back: 'The hemispheric rule (odd/even + 500 above 3,000 AGL), terrain/obstacle clearance, cloud clearance, and winds aloft (find the friendliest layer).',
      cite: '14 CFR 91.159; PHAK Ch. 16',
    },
    {
      slug: 'descent-plan',
      front: 'Rule of thumb: when to start descending from 6,500 to a 1,000-ft pattern at 500 fpm, 120 kt GS?',
      back: '~5,500 ft to lose ÷ 500 fpm = 11 min → at 2 NM/min ≈ 22 NM out.',
      why: '“Three times the altitude (in thousands) in miles” gets you close for GA descent gradients.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'ded-reckon-error',
      front: 'Your checkpoint arrives 2 minutes late. What do you do with that information?',
      back: 'Update: recompute groundspeed from actual elapsed time, revise ETA and fuel at destination, and correct any track error before it compounds.',
      why: 'Dead reckoning is a feedback loop, not a one-time plan. Small corrections early beat big ones late.',
      cite: 'PHAK Ch. 16',
    },
    {
      slug: 'sectional-currency',
      front: 'Why does chart currency matter for navigation specifically?',
      back: 'Frequencies, airspace boundaries, obstacles, and even airport status change every 56-day cycle — an old chart navigates you confidently into wrong airspace.',
      cite: 'FAA Chart Users’ Guide',
    },
    {
      slug: 'ndb-adf',
      front: 'How does an **ADF/NDB** differ from a VOR?',
      back: 'The ADF needle simply points at the NDB station (relative bearing from the nose) — no radials, no OBS, and it follows the station like a compass to a magnet.',
      why: 'Mostly retired in the lower 48, still alive in Alaska — where you’re headed.',
      cite: 'PHAK Ch. 16; AIM 1-1-2',
    },
    {
      slug: 'dme-slant',
      front: 'DME reads 6.0 over the station at 6,000 ft. Why not zero?',
      back: 'DME measures slant range, not ground distance — directly overhead it reads your altitude in NM (6,000 ft ≈ 1 NM).',
      why: 'Slant error matters close-in and high; negligible far away.',
      cite: 'AIM 1-1-7',
    },
    {
      slug: 'compass-course',
      front: 'A **compass correction card** shows “FOR 240 STEER 237.” What is this fixing?',
      back: 'Deviation — this airplane’s own magnetic interference on that heading. Apply after variation: magnetic heading → compass heading.',
      cite: 'PHAK Ch. 8, 16',
    },
    {
      slug: 'endurance-plan',
      front: 'Usable fuel 38 gal, burn 9 GPH. Endurance, and the number you actually plan with?',
      back: '~4.2 hours total — plan with 3.2–3.4 (land with an hour in the tanks).',
      why: 'Tanks run dry on paper exactly at the worst spot on the chart. The hour is for headwinds, deviations, and the runway you have to wait for.',
      cite: 'PHAK Ch. 16; 91.151',
    },
  ],
);
