import { deck } from '../types';

export const proceduresDeck = deck(
  {
    id: 'procedures',
    subject: 'procedures',
    title: 'Flight operations',
    description:
      'Pattern work, runway environment, wake turbulence, and what to do when the engine gets quiet.',
  },
  [
    {
      slug: 'pattern-standard',
      front: 'Standard traffic pattern: direction, and how do you learn the exceptions?',
      back: 'All turns to the LEFT unless the airport says otherwise — segmented circle markings, Chart Supplement, or “RP” (right pattern) note on the sectional.',
      cite: '14 CFR 91.126; AIM 4-3-3',
    },
    {
      slug: 'pattern-altitude',
      front: 'Typical **traffic pattern altitude** for a piston single?',
      back: '1,000 ft AGL (check the Chart Supplement — it varies).',
      cite: 'AIM 4-3-3',
    },
    {
      slug: 'pattern-entry',
      front: 'Recommended entry to a non-towered pattern?',
      back: 'At a 45° angle to the midpoint of the downwind, at pattern altitude.',
      why: 'Descending into the pattern on top of someone is the classic mid-air setup — be at TPA well before entry.',
      cite: 'AIM 4-3-3; AC 90-66',
    },
    {
      slug: 'pattern-legs',
      front: 'Name the five pattern legs in order after takeoff.',
      back: 'Upwind (departure), crosswind, downwind, base, final.',
      cite: 'AIM 4-3-3',
    },
    {
      slug: 'displaced-threshold',
      front: 'A **displaced threshold** (arrows leading to the bar) — what may you use it for?',
      back: 'Taxi, takeoff, and landing ROLLOUT — but not for touchdown. Land beyond the bar.',
      cite: 'AIM 2-3-3',
    },
    {
      slug: 'chevrons',
      front: 'Yellow **chevrons** before the runway?',
      back: 'Unusable for any aircraft operation — blast pad/stopway/EMAS. No taxi, no takeoff, no landing.',
      cite: 'AIM 2-3-3',
    },
    {
      slug: 'holdshort-marking',
      front: 'The runway **hold-short marking**: which side is which?',
      back: 'Two solid lines + two dashed lines. Solid side = you hold; cross only with clearance (towered). Dashed side = you’re ON the runway — get across, clear of it.',
      why: 'Exit the runway fully past the marking, then stop and clean up.',
      cite: 'AIM 2-3-5',
    },
    {
      slug: 'runway-signs',
      front: 'Red sign with white numbers vs black sign with yellow letters?',
      back: 'Red/white: runway holding position (mandatory). Black square/yellow: taxiway location (“you are on B”). Yellow/black arrow: direction to a taxiway.',
      why: '“Black square, you’re there.”',
      cite: 'AIM 2-3-8',
    },
    {
      slug: 'beacon-day',
      front: 'The airport rotating **beacon is on during the day** — what may that mean?',
      back: 'At an airport in Class B/C/D/E surface area: ground visibility below 3 SM and/or ceiling below 1,000 ft — i.e., below basic VFR minimums.',
      why: '“May” — there’s no regulatory guarantee. But treat a daytime beacon as a weather warning.',
      cite: 'AIM 2-1-9',
    },
    {
      slug: 'beacon-colors',
      front: 'Beacon colors: civilian land airport vs military?',
      back: 'Civilian: alternating white/green. Military: two quick whites then green. Water: white/yellow. Heliport: green/yellow/white.',
      cite: 'AIM 2-1-9',
    },
    {
      slug: 'vasi-papi',
      front: '**PAPI** lights: what do 2 white/2 red vs other combos mean?',
      back: '4 white: too high. 3W/1R: slightly high. 2W/2R: on glidepath. 1W/3R: slightly low. 4 red: TOO LOW.',
      why: 'VASI: “red over white, you’re alright; red over red, you’re dead.” At a Class D airport, large/turbine aircraft must stay at/above the glidepath.',
      cite: 'AIM 2-1-2; 14 CFR 91.129(e)',
    },
    {
      slug: 'taxi-wind',
      front: 'Taxiing in strong wind: control positions for a **quartering headwind** and **quartering tailwind**?',
      back: 'Quartering headwind: aileron UP into the wind (turn yoke toward it), elevator neutral. Quartering tailwind: aileron DOWN (yoke away), elevator DOWN.',
      why: '“Climb into the wind, dive away from it.”',
      cite: 'AFH Ch. 2',
    },
    {
      slug: 'wake-departure',
      front: 'Departing behind a large jet that just took off — your technique?',
      back: 'Rotate BEFORE its rotation point, climb above its path, and turn upwind/away. If you can’t out-climb the path, delay (2–3 min).',
      cite: 'AIM 7-4-6 area (wake turbulence avoidance)',
      unverified: true,
    },
    {
      slug: 'wake-arrival',
      front: 'Landing behind a large jet — your technique?',
      back: 'Stay at or above its final approach path and land BEYOND its touchdown point.',
      why: 'Vortices sink below the generating aircraft’s path — being above its path is the protection.',
      cite: 'AIM wake turbulence section',
      unverified: true,
    },
    {
      slug: 'lahso',
      front: 'Tower offers a **LAHSO** clearance (land and hold short). Must you accept?',
      back: 'No — the PIC may decline. Accept only if you’re certain of the available landing distance; student pilots should not accept LAHSO.',
      cite: 'AIM 4-3-11',
    },
    {
      slug: 'engine-fail-flow',
      front: 'Engine failure at altitude — the memory flow?',
      back: '**ABCDE**: Airspeed (best glide) · Best field (into wind if able) · Checklist (fuel, mixture, carb heat, mags, primer) · Declare (7700, Mayday 121.5) · Exit prep (belts, doors cracked, fuel/master off before touchdown).',
      cite: 'AFH Ch. 17; POH Section 3',
    },
    {
      slug: 'engine-fail-takeoff',
      front: 'Engine quits at 300 ft AGL on climbout. The cardinal rule?',
      back: 'Fly it down mostly straight ahead (small turns for obstacles) — do NOT attempt the turn-back. Pitch for glide immediately.',
      why: 'The “impossible turn” needs altitude your trainer doesn’t have; the stall/spin from the low turn kills more surely than the fence.',
      cite: 'AFH Ch. 17',
    },
    {
      slug: 'go-around',
      front: 'The go-around sequence?',
      back: 'Full power, carb heat off, pitch to arrest descent, flaps to the go-around setting (retract remainder in increments as you accelerate/climb), offset to see the runway if traffic below.',
      why: 'A go-around is a normal maneuver, not an admission of failure. Decide EARLY.',
      cite: 'AFH Ch. 8',
    },
    {
      slug: 'nordo',
      front: 'Radio dies inbound to a towered field (VFR). Plan?',
      back: 'Squawk 7600, stay outside/observe the flow, enter the pattern, watch the tower for light gun signals, acknowledge in flight by rocking wings (day) or flashing lights (night).',
      cite: 'AIM 4-2-13, 6-4-2; 14 CFR 91.125',
    },
    {
      slug: 'intercept',
      front: 'You get intercepted by military aircraft (TFR bust). First actions?',
      back: 'Follow the interceptor’s visual signals, tune 121.5 and attempt contact, squawk 7700 unless told otherwise. Comply first, argue later.',
      cite: 'AIM 5-6-2; 14 CFR 91.144 area',
      unverified: true,
    },
    {
      slug: 'seatbelt-brief',
      front: 'What must passengers be briefed on before takeoff?',
      back: 'How to fasten and unfasten belts/harnesses, and when they must be worn (taxi, takeoff, landing). Good practice adds doors, exits, sterile cockpit, and sick sacks.',
      cite: '14 CFR 91.107',
    },
    {
      slug: 'fuel-exhaustion',
      front: 'The #1 cause of engine stoppage in GA, and the defense?',
      back: 'Fuel mismanagement — exhaustion or starvation (fuel aboard, wrong tank/valve). Defense: visual quantity check, timed tank switches, land with a real reserve, know your burn rate.',
      cite: 'AOPA/NTSB safety data; PHAK',
      unverified: true,
    },
    {
      slug: 'sterile-approach',
      front: 'A stabilized approach: what gates should be set by short final?',
      back: 'On speed (±5), on glidepath, configured (flaps set), aligned, checklist complete, descent rate normal — ANY gate busted = go around.',
      cite: 'AFH Ch. 8',
    },
    {
      slug: 'runup-why',
      front: 'What is the runup actually verifying?',
      back: 'That the engine will make full, redundant power before you bet your life on it: mags (both firing/grounded), carb heat function, oil pressure/temp/vacuum/ammeter in range, controls free and correct.',
      cite: 'POH Section 4',
    },
  ],
);
