import { deck } from '../types';

/*
 * FAR 61 & 91 — the tested parts and the violated parts. Citations are the
 * point of this deck: an examiner wants "91.155" out of you almost as much
 * as the number itself.
 */

export const regsDeck = deck(
  {
    id: 'regs',
    subject: 'regs',
    title: 'Regulations (FAR 61 & 91)',
    description:
      'Certificates, currency, medicals, fuel, altitudes, right-of-way, equipment — with the citation for each.',
  },
  [
    {
      slug: 'pic-authority',
      front: 'Who is directly responsible for, and the final authority on, the operation of the aircraft?',
      back: 'The pilot in command.',
      why: 'In an emergency the PIC may deviate from ANY rule of Part 91 to the extent required — and send a written report only if the FAA asks.',
      cite: '14 CFR 91.3',
    },
    {
      slug: 'preflight-info',
      front: 'Required **preflight information** for any flight not in the vicinity of an airport?',
      back: 'Weather reports and forecasts, fuel requirements, alternatives available, known traffic delays, runway lengths, and takeoff/landing performance data.',
      why: 'Mnemonic **NWKRAFT**: NOTAMs, Weather, Known delays, Runway lengths, Alternatives, Fuel, Takeoff/landing data.',
      cite: '14 CFR 91.103',
    },
    {
      slug: 'vfr-fuel',
      front: 'Minimum **VFR fuel reserves**, day and night?',
      back: 'Enough to reach the first point of intended landing plus 30 minutes (day) or 45 minutes (night) at normal cruise.',
      why: 'Those are legal minimums, not plans. An hour reserve is the adult version.',
      cite: '14 CFR 91.151',
    },
    {
      slug: 'min-safe-alt',
      front: 'Minimum safe altitudes: **congested** vs **other than congested** vs **sparsely populated**?',
      back: 'Congested: 1,000 ft above the highest obstacle within 2,000 ft horizontally. Other: 500 ft above the surface. Sparse/water: no closer than 500 ft to any person, vessel, vehicle, or structure.',
      why: 'And everywhere: high enough to make an emergency landing without undue hazard to people below.',
      cite: '14 CFR 91.119',
    },
    {
      slug: 'row-categories',
      front: '**Right-of-way** between categories: who yields to whom?',
      back: 'Balloon > glider > airship > airplane/rotorcraft. Aircraft in distress beats everyone; aircraft towing/refueling beats other engine-driven aircraft.',
      why: 'The less maneuverable machine wins.',
      cite: '14 CFR 91.113',
    },
    {
      slug: 'row-converging',
      front: 'Two airplanes **converging** (not head-on) — who yields?',
      back: 'The aircraft on the LEFT yields; the one on the right has the right-of-way.',
      cite: '14 CFR 91.113(d)',
    },
    {
      slug: 'row-headon',
      front: 'Two aircraft approaching **head-on**?',
      back: 'Each alters course to the RIGHT.',
      cite: '14 CFR 91.113(e)',
    },
    {
      slug: 'row-overtaking',
      front: '**Overtaking** another aircraft — pass on which side?',
      back: 'The right. The aircraft being overtaken has the right-of-way.',
      cite: '14 CFR 91.113(f)',
    },
    {
      slug: 'row-landing',
      front: 'Two aircraft approaching to **land**?',
      back: 'The lower aircraft has the right-of-way — but don’t use that rule to cut in front of one on final.',
      cite: '14 CFR 91.113(g)',
    },
    {
      slug: 'alcohol',
      front: 'Alcohol rules for pilots: hours, BAC, and passengers?',
      back: '8 hours bottle-to-throttle, 0.04 BAC max, not while under the influence — and you may not carry a passenger who appears intoxicated (except in an emergency).',
      why: '“8 hours” is the floor; hangover impairment lasts far longer and is also “under the influence.”',
      cite: '14 CFR 91.17',
    },
    {
      slug: 'belts',
      front: 'Seatbelt/harness rules for **you** and **passengers**?',
      back: 'Crew: belt on at all times at your station, shoulder harness for takeoff/landing (if installed). Passengers: briefed, and belts fastened for taxi, takeoff, and landing.',
      cite: '14 CFR 91.105, 91.107',
    },
    {
      slug: 'flight-review',
      front: 'The **flight review**: how often, what does it take?',
      back: 'Every 24 calendar months: minimum 1 hour flight training + 1 hour ground training with an authorized instructor.',
      why: '“Calendar months” = through the end of the month. A checkride or new rating also resets it.',
      cite: '14 CFR 61.56',
    },
    {
      slug: 'passenger-currency',
      front: 'To carry **passengers**, what recent experience do you need?',
      back: '3 takeoffs and landings in the preceding 90 days, in the same category/class (and type if required). Tailwheel: full stop.',
      cite: '14 CFR 61.57(a)',
    },
    {
      slug: 'night-currency',
      front: '**Night** passenger currency — the specifics?',
      back: '3 takeoffs and landings to a FULL STOP between 1 hour after sunset and 1 hour before sunrise, within the preceding 90 days.',
      why: 'Note the three different night definitions: lights on (sunset–sunrise, 91.209), logging night (end of evening civil twilight, 61.51), currency (the 1-hour window, 61.57).',
      cite: '14 CFR 61.57(b)',
    },
    {
      slug: 'medical-duration',
      front: 'A **third-class medical** lasts how long?',
      back: 'Under 40 at exam: 60 calendar months. 40 or over: 24 calendar months.',
      why: 'BasicMed is an alternative after any post-2006 medical: online course + physician exam, with aircraft/altitude limits that don’t bother a trainer.',
      cite: '14 CFR 61.23',
    },
    {
      slug: 'private-privileges',
      front: 'May a **private pilot** be paid to fly? The main exceptions?',
      back: 'Not for compensation or hire. Exceptions include: pro-rata sharing of operating expenses with passengers (pilot pays at least an equal share), flights incidental to your business, some charitable event flights, aircraft sales demos (200+ hrs), towing gliders (with requirements).',
      why: 'Pro-rata means fuel/oil/airport fees/rental split equally — and you need a common purpose for the trip.',
      cite: '14 CFR 61.113',
    },
    {
      slug: 'documents-personal',
      front: 'Documents YOU must carry to act as PIC?',
      back: 'Pilot certificate, government photo ID, and medical certificate (or BasicMed compliance).',
      cite: '14 CFR 61.3',
    },
    {
      slug: 'documents-aircraft',
      front: 'Documents that must be **aboard the aircraft**?',
      back: '**ARROW**: Airworthiness certificate (displayed), Registration, Radio license (international only), Operating limitations (AFM/POH + placards), Weight & balance data.',
      cite: '14 CFR 91.203, 91.9',
    },
    {
      slug: 'inspections',
      front: 'Required **aircraft inspections** for a rental trainer?',
      back: '**AAV1ATE**: Annual (12 cal. months), Airworthiness Directives (as required), VOR (30 days, IFR only), 100-hour (if for hire/instruction), Altimeter/pitot-static (24 mo, IFR), Transponder (24 cal. months), ELT (12 cal. months; battery at 1 hr cumulative use or 50% life).',
      cite: '14 CFR 91.409, 91.411, 91.413, 91.207',
    },
    {
      slug: '100hr-vs-annual',
      front: 'Can a **100-hour** inspection substitute for an annual? The reverse?',
      back: 'An annual can substitute for a 100-hour, never the reverse. The 100-hour may be exceeded by up to 10 hours to REACH a place of inspection — excess counts against the next 100.',
      cite: '14 CFR 91.409(b)',
    },
    {
      slug: 'day-vfr-equip',
      front: 'Minimum equipment, **day VFR** (the memory aid)?',
      back: '**A TOMATO FLAMES**: Airspeed, Tach, Oil pressure, Manifold pressure (if applicable), Altimeter, Temp gauge (liquid-cooled), Oil temp (air-cooled), Fuel gauges, Landing gear position (if retractable), Anticollision lights (post-1996), Magnetic compass, ELT, Seatbelts.',
      cite: '14 CFR 91.205(b)',
    },
    {
      slug: 'night-vfr-equip',
      front: 'ADDITIONAL equipment for **night VFR**?',
      back: '**FLAPS**: Fuses (spares) or breakers, Landing light (if for hire), Anticollision lights, Position lights, Source of electrical power.',
      cite: '14 CFR 91.205(c)',
    },
    {
      slug: 'inop-equipment',
      front: 'Something breaks that isn’t required. Can you fly? What must be done?',
      back: 'Possibly — with no MEL: the item must not be required by 91.205/type design/ADs, and it must be deactivated or removed AND placarded “INOPERATIVE”; PIC then determines it’s safe.',
      why: 'The examiner wants the 91.213(d) walk-through, not a shrug. When in doubt, a mechanic and a logbook entry.',
      cite: '14 CFR 91.213(d)',
    },
    {
      slug: 'position-lights',
      front: 'When must **position (nav) lights** be on?',
      back: 'Sunset to sunrise.',
      why: 'Anticollision lights: whenever the aircraft is operated, unless the PIC judges them a safety hazard (e.g., strobe reflection in cloud).',
      cite: '14 CFR 91.209',
    },
    {
      slug: 'supplemental-o2',
      front: '**Supplemental oxygen** altitudes for crew and passengers?',
      back: 'Crew: required above 12,500 MSL cabin altitude for flight >30 min; required at all times above 14,000. Passengers: must be PROVIDED (not necessarily used) above 15,000.',
      why: '“12-5 for 30, 14 for crew, 15 provide.”',
      cite: '14 CFR 91.211',
    },
    {
      slug: 'altimeter-setting',
      front: 'Below 18,000 MSL, what do you set the altimeter to?',
      back: 'The current setting of a station within 100 NM; if unavailable, departure airport elevation before takeoff.',
      cite: '14 CFR 91.121',
    },
    {
      slug: 'transponder-alt',
      front: 'Transponder Mode C: when must altitude reporting be on?',
      back: 'Whenever operating in controlled airspace with an operable transponder — turn it on (ALT) as early as practical and leave it on.',
      cite: '14 CFR 91.215; AIM 4-1-20',
    },
    {
      slug: 'formation-drop',
      front: 'Rules on **dropping objects** and **formation flight** with passengers for hire?',
      back: 'Dropping: allowed only if reasonable precautions avoid hazard to persons/property. Formation: only by prior arrangement of each PIC; never with passengers carried for hire.',
      cite: '14 CFR 91.15, 91.111',
    },
    {
      slug: 'careless',
      front: 'The catch-all regulation the FAA can always charge?',
      back: '91.13 — careless or reckless operation endangering life or property.',
      why: 'It rides along with nearly every enforcement action. “Legal but dumb” often lands here.',
      cite: '14 CFR 91.13',
    },
    {
      slug: 'ppl-aero-exp',
      front: 'Private pilot **aeronautical experience** headline numbers (Part 61, airplane SEL)?',
      back: '40 hr total · 20 hr training · 10 hr solo, including: 3 hr XC training, 3 hr night (with a 100 NM night XC + 10 night T/O-landings), 3 hr instrument training, 3 hr checkride prep within 2 cal. months, 5 hr solo XC, one 150 NM solo XC with landings at 3 points (one leg ≥50 NM straight-line).',
      cite: '14 CFR 61.109(a)',
    },
    {
      slug: 'solo-xc-def',
      front: 'For private pilot requirements, what counts as a **cross-country**?',
      back: 'A landing more than 50 NM straight-line from the departure point.',
      cite: '14 CFR 61.1(b)',
    },
    {
      slug: 'student-limits',
      front: 'Three things a **student pilot** may never do on solo?',
      back: 'Carry passengers, fly for compensation/hire, or fly with visibility below 3 SM day (5 SM night) / without visual surface reference.',
      why: 'Plus: no international flight, and only with the required endorsements current.',
      cite: '14 CFR 61.89',
    },
    {
      slug: 'change-address',
      front: 'You move. How long before you must notify the FAA?',
      back: 'You may not exercise your certificate more than 30 days after the move without notifying the FAA in writing (airmen certification branch / online).',
      cite: '14 CFR 61.60',
    },
    {
      slug: 'accident-notify',
      front: 'Events requiring **immediate NTSB notification**?',
      back: 'An accident, plus listed incidents: flight control system failure, crew incapacitation, turbine failure with escaped debris, in-flight fire, mid-air collision, >$25,000 property damage, overdue aircraft believed in an accident.',
      why: 'Accident = death/serious injury/substantial damage. Report form follows within 10 days for accidents (only on request for incidents).',
      cite: '49 CFR 830.5, 830.15',
    },
    {
      slug: 'preventive-maint',
      front: 'May a private pilot perform **maintenance**?',
      back: 'Preventive maintenance only — e.g., oil changes, tire changes, replacing bulbs/spark plugs — on an aircraft you own/operate, with a proper logbook entry.',
      cite: '14 CFR 43.3(g), Part 43 Appendix A(c)',
    },
    {
      slug: 'atc-instructions',
      front: 'You receive an ATC instruction you think is wrong. Options?',
      back: 'You must comply with ATC instructions in areas where ATC is exercised — unless an emergency or safety requires deviation (“unable” is the tool). Ask for clarification if unsure; deviation for a TCAS/safety reason gets reported if requested.',
      cite: '14 CFR 91.123',
    },
    {
      slug: 'sim-instrument',
      front: 'Flying under the hood (simulated instrument): what does 91.109 require?',
      back: 'A safety pilot in the other control seat, appropriately rated in the aircraft category/class, and dual controls.',
      cite: '14 CFR 91.109(c)',
    },
    {
      slug: 'elt-when',
      front: 'When may you legally fly **without an ELT**?',
      back: 'Narrow cases: e.g., newly acquired aircraft ferry, training within 50 NM of the home airport, and while the ELT is removed for repair (up to 90 days, placarded).',
      cite: '14 CFR 91.207(e),(f)',
    },
    {
      slug: 'aerobatic',
      front: '**Aerobatic flight** — where is it prohibited, and when are parachutes required?',
      back: 'Prohibited: over congested areas, open-air assemblies, within Class B/C/D/E surface areas, on airways, below 1,500 AGL, under 3 SM vis. Parachutes: required for occupants (other than crew) beyond 60° bank or 30° pitch.',
      cite: '14 CFR 91.303, 91.307',
    },
    {
      slug: 'vfr-otT',
      front: 'Can a private pilot fly **VFR over-the-top** (above a solid layer)?',
      back: 'Yes — it’s legal for a private pilot without an instrument rating (student pilots cannot). You must be able to maintain VFR the whole way and get down VFR.',
      why: 'Legal, and one of the classic PNW traps: the “sucker hole” closes behind you over the Cascades.',
      cite: '14 CFR 61.89; PHAK',
    },
  ],
);
