import { deck } from '../types';

export const systemsDeck = deck(
  {
    id: 'systems',
    subject: 'systems',
    title: 'Aircraft systems',
    description:
      'Engine, ignition, fuel, electrical, flight instruments — what each does and how each fails.',
  },
  [
    {
      slug: 'four-stroke',
      front: 'The four strokes of your trainer’s engine, in order?',
      back: 'Intake, compression, power, exhaust.',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'magnetos',
      front: 'Why do aircraft engines have **two magnetos**, and what powers them?',
      back: 'Redundancy and better combustion (two plugs per cylinder). They are self-contained — engine-driven, completely independent of battery/alternator.',
      why: 'Master OFF, the engine keeps running. That’s why the mag check matters and why props are treated as live.',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'mag-check',
      front: 'On the runup mag check you see NO rpm drop on one mag. Good news?',
      back: 'No — a missing drop suggests a broken ground (P-lead): that magneto may be HOT even with the switch off.',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'carb-ice-conditions',
      front: 'Conditions most likely to produce **carburetor ice**?',
      back: 'High humidity and temperatures roughly 20–70°F — venturi cooling can be 30°C+, so carb ice happens on warm days, especially at LOW power (descents).',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'carb-ice-sign',
      front: 'First sign of carb ice with a **fixed-pitch prop**, and the fix?',
      back: 'An unexplained RPM drop (engine roughness follows). Fix: full carb heat — expect a further drop and roughness as ice melts through, then recovery.',
      why: 'With a constant-speed prop, the sign is a manifold pressure drop instead.',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'carb-heat-effect',
      front: 'What does carb heat do to the mixture and power?',
      back: 'Hot air is less dense → mixture enriches, power drops slightly. That’s also why it’s applied BEFORE closing the throttle on descent.',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'mixture-why',
      front: 'Why lean the mixture as you climb?',
      back: 'Air density drops but fuel metering doesn’t — the mixture enriches with altitude. Leaning restores the correct fuel/air ratio for power, smoothness, and plug health.',
      why: 'Full-rich at altitude fouls plugs and wastes fuel; too lean at high power overheats.',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'detonation',
      front: '**Detonation** vs **pre-ignition**?',
      back: 'Detonation: explosive combustion of the fuel/air charge (from high temps/pressures, wrong or low-grade fuel). Pre-ignition: burning starts EARLY from a hot spot (glowing deposit). Both destroy engines; both show as roughness/high CHT/power loss.',
      why: 'Cures: enrich, reduce power, open cowl flaps if fitted, lower the nose for cooling.',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'fuel-grades',
      front: 'Your engine calls for 100LL and it’s unavailable. Higher or lower grade?',
      back: 'The next HIGHER approved grade — never lower. Lower octane invites detonation.',
      why: '100LL is blue. Jet fuel (clear/straw, smells like kerosene) in a piston engine is a killer — sump checks exist for this.',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'fuel-sump',
      front: 'What are you looking for when you sump the tanks?',
      back: 'Water (sits at the bottom as a distinct bubble), sediment, and correct fuel color/smell (blue 100LL, not clear jet-A).',
      cite: 'PHAK Ch. 7; AFM',
    },
    {
      slug: 'alternator-fail',
      front: 'The ammeter shows a **discharge** in cruise. What happened and what’s the plan?',
      back: 'Alternator failure — the battery is now the only source. Reduce electrical load, plan for the battery’s limited time, and land before you lose radios/flaps (engine keeps running on magnetos).',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'gyro-power',
      front: 'Which gyro instruments are **vacuum** vs **electric** in a classic trainer?',
      back: 'Vacuum: attitude indicator and heading indicator. Electric: turn coordinator.',
      why: 'Split sources on purpose: lose vacuum, the turn coordinator survives (and vice versa). Cross-check catches the liar.',
      cite: 'PHAK Ch. 8',
    },
    {
      slug: 'pitot-static-instr',
      front: 'Which instruments use the **pitot-static** system, and which use static only?',
      back: 'Airspeed uses pitot AND static. Altimeter and VSI use static only.',
      cite: 'PHAK Ch. 8',
    },
    {
      slug: 'pitot-blocked',
      front: 'Pitot tube (ram AND drain) blocked, static open — what does the ASI do?',
      back: 'Acts like an altimeter: over-reads as you climb, under-reads as you descend, frozen in level flight.',
      why: 'Classic icing scenario. Pitot heat is the vaccine.',
      cite: 'PHAK Ch. 8',
    },
    {
      slug: 'static-blocked',
      front: '**Static port** blocked — what do the three instruments do?',
      back: 'Altimeter freezes, VSI reads zero, ASI errors: under-reads above the blockage altitude, over-reads below it.',
      why: 'Alternate static (from the cabin) fixes it — expect slightly high ASI/altimeter readings since cabin pressure is a touch low.',
      cite: 'PHAK Ch. 8',
    },
    {
      slug: 'asi-arcs',
      front: 'Airspeed indicator arcs: white, green, yellow, red line?',
      back: 'White: flap operating range (VS0→VFE). Green: normal (VS1→VNO). Yellow: caution — smooth air only (VNO→VNE). Red line: VNE, never exceed.',
      why: 'Va is NOT marked — it varies with weight, which is exactly why they make you memorize it.',
      cite: 'PHAK Ch. 8',
    },
    {
      slug: 'v-speeds-def',
      front: 'Define VS0 and VS1.',
      back: 'VS0: stall speed in landing configuration (flaps down). VS1: stall speed in a specified configuration (typically clean).',
      cite: 'PHAK Ch. 8; 14 CFR 1.2',
    },
    {
      slug: 'altimeter-error',
      front: '“High to low, look out below” — what’s the actual error?',
      back: 'Flying from high pressure/warm air into low pressure/cold air with an old setting, the altimeter OVER-reads — you are LOWER than indicated.',
      cite: 'PHAK Ch. 8',
    },
    {
      slug: 'compass-ands',
      front: 'Magnetic compass **acceleration** error (northern hemisphere)?',
      back: '**ANDS**: Accelerate → North indication; Decelerate → South. On east/west headings.',
      cite: 'PHAK Ch. 8',
    },
    {
      slug: 'compass-unos',
      front: 'Magnetic compass **turning** error?',
      back: '**UNOS** — Undershoot North, Overshoot South: rolling out on a northerly heading, lead the rollout (compass lags); on a southerly heading, roll out past it (compass leads). Error is greatest on north/south headings.',
      cite: 'PHAK Ch. 8',
    },
    {
      slug: 'variation-deviation',
      front: '**Variation** vs **deviation**?',
      back: 'Variation: difference between true and magnetic north (charted isogonic lines). Deviation: compass error from the aircraft’s own magnetic fields (compass correction card).',
      why: 'True ± variation = magnetic; magnetic ± deviation = compass.',
      cite: 'PHAK Ch. 8, 16',
    },
    {
      slug: 'hi-precession',
      front: 'Why must the **heading indicator** be reset, and to what?',
      back: 'Gyro precession/drift — realign it to the magnetic compass every ~15 minutes, in straight-and-level unaccelerated flight.',
      cite: 'PHAK Ch. 8',
    },
    {
      slug: 'oil-functions',
      front: 'Engine oil does what four jobs?',
      back: 'Lubricates, cools, seals, and cleans (carries contaminants to the filter).',
      why: 'Low oil pressure + rising oil temp = land now; that’s the failure signature.',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'priming-flooded',
      front: 'Signs of a **flooded** engine on start, and the usual fix?',
      back: 'Fuel smell, no start with black smoke risk — mixture idle-cutoff, throttle open, crank to clear, then normal start as it fires.',
      cite: 'AFM/POH',
      unverified: true,
    },
    {
      slug: 'constant-speed',
      front: 'On a constant-speed prop airplane, what do the throttle and prop levers each control?',
      back: 'Throttle → manifold pressure (power). Prop lever → RPM via blade pitch.',
      why: 'Not on your first trainer, but it shows up on the written. “Squawk high, RPM low” — avoid high MP with low RPM.',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'carb-vs-injection',
      front: '**Carburetor** vs **fuel injection** — the practical trade?',
      back: 'Carburetor: simpler, but makes its own ice and mixes less evenly. Injection: no carb ice, precise per-cylinder metering — but hot-start quirks and vapor lock instead.',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'fuel-selector',
      front: 'When does the POH have you run the fuel selector on **BOTH** vs a single tank?',
      back: 'High-wing gravity systems typically feed BOTH for takeoff/landing (no tank-switching errors low). Single-tank selections manage imbalance in cruise. Low-wing airplanes usually force left/right — with a boost pump for switching.',
      cite: 'POH Section 7',
    },
    {
      slug: 'boost-pump',
      front: 'What is the **electric fuel (boost) pump** for in a low-wing trainer?',
      back: 'Backup pressure for the engine-driven pump: on for takeoff/landing, tank switches, and if the engine pump fails. Gravity can’t feed uphill from a low wing.',
      cite: 'PHAK Ch. 7; POH',
    },
    {
      slug: 'primer',
      front: 'What does the **primer** do, and its cold-start role?',
      back: 'Squirts fuel directly into the intake near the cylinders, bypassing the carburetor — vaporizable fuel for a cold engine that can’t suck a good mixture yet. Locked after use (an unlocked primer leans the mixture in flight).',
      cite: 'PHAK Ch. 7; POH',
    },
    {
      slug: 'impulse-coupling',
      front: 'That “snap” you hear turning the prop — what is it, and why does it matter?',
      back: 'The magneto’s impulse coupling: a spring mechanism that spins the mag fast and retards spark for starting. It’s also why a “dead” engine can fire from one blade pull — treat every prop as hot.',
      cite: 'PHAK Ch. 7',
      unverified: true,
    },
    {
      slug: 'breaker-reset',
      front: 'A circuit breaker pops in flight. Reset policy?',
      back: 'Once, at most — and only if the circuit matters for the flight and there’s no smell/smoke. It popped for a reason; a second pop means leave it out.',
      cite: 'POH; AFH',
    },
    {
      slug: 'avionics-master',
      front: 'Why is there a separate **avionics master** switch?',
      back: 'To keep voltage spikes from engine start/shutdown away from the radios and GPS — avionics off before start and before master off.',
      cite: 'POH Section 7',
    },
    {
      slug: 'ammeter-loadmeter',
      front: '**Ammeter** vs **loadmeter** — what does each show?',
      back: 'Ammeter (center-zero): battery charge/discharge — discharge means the alternator isn’t keeping up. Loadmeter: alternator output as a fraction of capacity — zero means alternator offline.',
      cite: 'PHAK Ch. 7',
    },
    {
      slug: 'oil-pressure-start',
      front: 'After start, when must you see **oil pressure**, or shut down?',
      back: 'Within about 30 seconds in warm weather (up to ~60 in winter, per POH). No pressure = bearings running dry = shut down now.',
      cite: 'POH Section 4',
      unverified: true,
    },
    {
      slug: 'egt-leaning',
      front: 'Leaning with an **EGT gauge** — the typical method?',
      back: 'Lean until peak EGT, then enrich to the POH target (often ~50–100°F rich of peak for cruise power). Rough/rich engines waste fuel; over-lean at high power overheats.',
      cite: 'POH Section 4; PHAK Ch. 7',
    },
    {
      slug: 'vacuum-fail-signs',
      front: 'How does a **vacuum failure** actually present in the cockpit?',
      back: 'Quietly: the suction gauge drops, then the attitude and heading indicators slowly wander as gyros spin down over minutes. Cross-check catches it; trusting a dying AI in cloud kills.',
      cite: 'PHAK Ch. 8',
    },
    {
      slug: 'static-wicks',
      front: 'The little rods on the trailing edges — what are **static wicks** for?',
      back: 'Bleeding off precipitation static so it doesn’t hash your radios and nav reception.',
      cite: 'PHAK Ch. 7',
      unverified: true,
    },
    {
      slug: 'pitot-heat-check',
      front: 'How do you check **pitot heat** on preflight?',
      back: 'Switch it on briefly and carefully feel the probe warm (seconds only — it burns), then off before it cooks on the ground.',
      cite: 'POH Section 4',
    },
    {
      slug: 'stall-horn',
      front: 'How does the **stall warning** know before you do?',
      back: 'A vane/port near the leading edge senses the stagnation point moving down/aft as AOA rises — triggering the horn ~5–10 kt above stall.',
      cite: 'PHAK Ch. 5, 8',
      unverified: true,
    },
  ],
);
