import { deck } from '../types';

/*
 * Two decks: METAR/TAF decoding (the urgent skill) and weather theory.
 * The METAR Lab tool generates endless practice reports; these cards teach
 * the symbols the lab assumes you know.
 */

export const metarDeck = deck(
  {
    id: 'metar',
    subject: 'weather',
    title: 'METAR & TAF decoding',
    description:
      'Every symbol you’ll meet in a report or forecast, plus flight categories and the products around them.',
  },
  [
    {
      slug: 'metar-order',
      front: 'The element order of a **METAR**?',
      back: 'Station · time (Z) · wind · visibility · weather · sky · temp/dewpoint · altimeter · remarks.',
      why: '`KTIW 201853Z 17008KT 10SM FEW035 18/09 A3002 RMK AO2` — learn the skeleton and every report reads itself.',
      cite: 'AC 00-45 (Aviation Weather Services)',
    },
    {
      slug: 'wind-group',
      front: 'Decode wind: `35012G20KT`',
      back: 'From 350° true at 12 knots, gusting 20.',
      why: 'METAR winds are TRUE north; tower/ATIS winds are MAGNETIC. “If you read it, it’s true; if you hear it, it’s magnetic.”',
      cite: 'AC 00-45',
    },
    {
      slug: 'wind-vrb',
      front: 'Decode: `VRB04KT` and `00000KT`',
      back: 'Wind variable in direction at 4 knots · wind calm.',
      why: 'A `180V240` group after the wind means direction varying between 180° and 240°.',
      cite: 'AC 00-45',
    },
    {
      slug: 'vis',
      front: 'Decode visibility: `1 1/2SM`',
      back: 'One and one-half statute miles.',
      why: 'US METARs use statute miles. `M1/4SM` means less than a quarter mile.',
      cite: 'AC 00-45',
    },
    {
      slug: 'intensity',
      front: 'What do `-`, (nothing), and `+` mean before a weather code?',
      back: 'Light, moderate, heavy. `-RA` light rain, `+SN` heavy snow.',
      cite: 'AC 00-45',
    },
    {
      slug: 'vc',
      front: 'What does `VC` mean, as in `VCSH`?',
      back: 'In the vicinity — within 5 to 10 SM of the station, not at it.',
      cite: 'AC 00-45',
    },
    {
      slug: 'descriptors',
      front: 'Decode the descriptors: `TS`, `SH`, `FZ`, `BL`',
      back: 'Thunderstorm · showers · freezing · blowing.',
      why: '`FZRA` (freezing rain) is an emergency-grade icing hazard for a trainer. `TSRA` = thunderstorm with rain.',
      cite: 'AC 00-45',
    },
    {
      slug: 'precip-codes',
      front: 'Decode: `RA`, `DZ`, `SN`, `GR`, `PL`',
      back: 'Rain · drizzle · snow · hail · ice pellets.',
      why: 'Ice pellets aloft mean freezing rain is somewhere above you — rain froze on the way down.',
      cite: 'AC 00-45',
    },
    {
      slug: 'obscurations',
      front: 'Decode: `BR`, `FG`, `HZ`, `FU`',
      back: 'Mist · fog · haze · smoke.',
      why: 'BR vs FG is a visibility split: mist = visibility 5/8 SM or more, fog = less than 5/8 SM.',
      cite: 'AC 00-45',
    },
    {
      slug: 'sky-amounts',
      front: 'Cloud cover in eighths for `FEW`, `SCT`, `BKN`, `OVC`?',
      back: 'FEW 1–2 · SCT 3–4 · BKN 5–7 · OVC 8 oktas.',
      why: 'Heights are in hundreds of feet AGL: `BKN035` = broken at 3,500 AGL.',
      cite: 'AC 00-45',
    },
    {
      slug: 'ceiling-def',
      front: 'What counts as a **ceiling**?',
      back: 'The lowest BKN or OVC layer (or vertical visibility into an obscuration).',
      why: 'FEW and SCT are not ceilings. `SCT008 BKN030` → ceiling 3,000.',
      cite: 'P/CG “CEILING”',
    },
    {
      slug: 'vv',
      front: 'Decode: `VV004`',
      back: 'Sky obscured, vertical visibility 400 ft — an indefinite ceiling of 400.',
      why: 'Fog all the way down. This is a stay-home number for VFR.',
      cite: 'AC 00-45',
    },
    {
      slug: 'temp-dew',
      front: 'Decode: `18/16` and `M02/M04`',
      back: '18°C temp, 16°C dewpoint · −2°C temp, −4°C dewpoint.',
      why: 'A 2° spread means air is near saturation — fog or low clouds are close, especially with cooling.',
      cite: 'AC 00-45',
    },
    {
      slug: 'altimeter',
      front: 'Decode: `A2992`',
      back: 'Altimeter setting 29.92 inches of mercury.',
      cite: 'AC 00-45',
    },
    {
      slug: 'ao2',
      front: 'In remarks: what’s the difference between `AO1` and `AO2`?',
      back: 'Both are automated stations; AO2 has a precipitation discriminator (can tell rain from snow), AO1 cannot.',
      cite: 'AC 00-45',
    },
    {
      slug: 'speci',
      front: 'What is a **SPECI**?',
      back: 'An unscheduled special METAR issued when conditions change significantly between hourly reports.',
      why: 'A SPECI landing in your briefing is the weather telling you it’s evolving fast.',
      cite: 'AC 00-45',
    },
    {
      slug: 'flight-cat',
      front: 'Ceiling/visibility for **VFR, MVFR, IFR, LIFR** categories?',
      back: 'VFR: >3,000 and >5 SM · MVFR: 1,000–3,000 and/or 3–5 SM · IFR: 500–999 and/or 1–3 SM · LIFR: <500 and/or <1 SM.',
      why: 'Category is the worse of ceiling or visibility. These color the dots on weather maps: green/blue/red/magenta.',
      cite: 'AC 00-45',
    },
    {
      slug: 'taf-scope',
      front: 'What area and duration does a **TAF** cover?',
      back: '5 SM around the airport, usually 24 hours (30 at some hubs), issued four times daily.',
      cite: 'AC 00-45',
    },
    {
      slug: 'taf-fm',
      front: 'In a TAF: `FM201530`',
      back: 'From the 20th at 1530Z, a rapid and complete change to the conditions that follow.',
      cite: 'AC 00-45',
    },
    {
      slug: 'taf-tempo',
      front: 'In a TAF: `TEMPO 2018/2021 3SM -RA BR`',
      back: 'Temporary fluctuations — lasting under an hour at a time — between 1800Z and 2100Z on the 20th: 3 SM, light rain, mist.',
      cite: 'AC 00-45',
    },
    {
      slug: 'taf-becmg',
      front: 'TAF `BECMG` vs `FM` — the difference?',
      back: 'BECMG: gradual change over the stated window. FM: rapid change at that time.',
      cite: 'AC 00-45',
    },
    {
      slug: 'prob30',
      front: 'TAF: `PROB30 2104/2107 1SM TSRA`',
      back: '30% probability of 1 SM in thunderstorm/rain between 0400–0700Z on the 21st.',
      why: 'PROB30 in a TAF is meteorologist for “I wouldn’t bet your checkride on it staying nice.”',
      cite: 'AC 00-45',
    },
    {
      slug: 'airmets',
      front: 'The three **AIRMET** types and what each warns of?',
      back: 'Sierra: IFR conditions/mountain obscuration · Tango: moderate turbulence, 30+ kt surface winds · Zulu: moderate icing, freezing level.',
      why: 'AIRMETs matter to light aircraft. Mountain obscuration is a constant PNW companion.',
      cite: 'AC 00-45; AIM 7-1-6',
    },
    {
      slug: 'sigmet',
      front: '**SIGMET** vs **Convective SIGMET**?',
      back: 'SIGMET: severe non-convective hazards (severe ice, severe turbulence, dust/ash). Convective SIGMET: thunderstorm-related — severe by definition, hazardous to ALL aircraft.',
      cite: 'AIM 7-1-6',
    },
    {
      slug: 'pirep',
      front: 'In a PIREP: `UA /OV KTIW /TM 1845 /FL045 /TP C172 /TB LGT`',
      back: 'Routine pilot report over Tacoma Narrows at 1845Z, 4,500 ft, C172, light turbulence.',
      why: 'UUA would be urgent. Give PIREPs — you’re the only weather sensor at 4,500 over the Sound.',
      cite: 'AIM 7-1-19',
    },
    {
      slug: 'atis-what',
      front: 'What is **ATIS** and when do you get it?',
      back: 'Recorded airport info (weather, runway in use, NOTAMs) on its own frequency, updated hourly or on significant change — get it BEFORE calling approach/tower and report the letter.',
      cite: 'AIM 4-1-13',
    },
    {
      slug: 'awos-asos',
      front: '**ASOS/AWOS** vs ATIS?',
      back: 'ASOS/AWOS are automated weather sensors broadcasting continuously (typical at non-towered fields); ATIS is a recorded summary at towered fields.',
      cite: 'AIM 4-1-13; AC 00-45',
    },
    {
      slug: 'metar-taf-which',
      front: 'METAR vs TAF — which is observation, which is forecast?',
      back: 'METAR: observation (what IS). TAF: forecast (what’s EXPECTED).',
      why: 'Exam answers that mix these up are free points.',
      cite: 'AC 00-45',
    },
  ],
);

export const wxTheoryDeck = deck(
  {
    id: 'wx-theory',
    subject: 'weather',
    title: 'Weather theory',
    description:
      'Stability, fronts, fog, icing, thunderstorms, and the mountain effects that own the Pacific Northwest.',
  },
  [
    {
      slug: 'std-atmos',
      front: 'Standard atmosphere at sea level: temp, pressure, lapse rate?',
      back: '15°C / 29.92 inHg, temperature lapsing ~2°C per 1,000 ft.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'stable-signs',
      front: 'You’re flying in **stable** air. What do you see and feel?',
      back: 'Stratiform clouds, steady precipitation, smooth ride, poor visibility (haze and pollutants trapped).',
      why: 'Unstable is the mirror: cumuliform, showery, turbulent, good visibility between the bumps.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'stability-cause',
      front: 'What determines atmospheric **stability**?',
      back: 'The actual lapse rate vs. the adiabatic rates — cold air aloft over warm air below is unstable; warm over cold (inversion) is very stable.',
      why: 'Moist air condensing releases heat, which is why moist air destabilizes more easily.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'inversion',
      front: 'A **temperature inversion** gives what flying conditions?',
      back: 'Smooth, stable air with poor visibility (trapped haze/smog) — and possible wind shear at the inversion layer.',
      why: 'Classic Puget Sound winter: weeks of gray under an inversion cap.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'dewpoint-fog',
      front: 'Temp/dewpoint spread that should make you think **fog**?',
      back: 'Within about 2°C (4°F) and converging — expect fog or very low cloud, especially evening/early morning.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'radiation-fog',
      front: 'Recipe for **radiation fog**?',
      back: 'Clear night, calm/light wind, moist air over land — the ground radiates heat away and the air above it saturates.',
      why: 'Burns off after sunrise. Valley floors first — Chehalis on a fall morning.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'advection-fog',
      front: 'Recipe for **advection fog**, and why is it worse than radiation fog?',
      back: 'Warm moist air flowing over a colder surface — needs wind, so it can persist for days and even thicken. Coastal specialty.',
      why: 'Marine layer pushing into Puget Sound is advection fog. It does not care that the sun came up.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'upslope-steam',
      front: '**Upslope** fog and **steam** fog — recipes?',
      back: 'Upslope: moist air forced up terrain, cooling adiabatically. Steam: cold air over warm water, moisture rises like a boiling pot (winter over the Sound).',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'cold-front',
      front: 'Weather character of a **cold front**?',
      back: 'Fast-moving, steep slope: narrow band of cumuliform clouds, showers/thunderstorms, gusty shifting winds, then rapid clearing and good visibility.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'warm-front',
      front: 'Weather character of a **warm front**?',
      back: 'Slow, shallow slope: hundreds of miles of layered clouds thickening in sequence (cirrus → nimbostratus), steady precip, low ceilings, poor visibility — arriving well ahead of the surface front.',
      why: 'Freezing rain risk in winter: warm rain falling into cold air below.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'occluded',
      front: 'An **occluded front** gives what weather?',
      back: 'A mix of both parents: warm-front low ceilings and steady precip plus cold-front showers and turbulence, as the cold front overtakes the warm.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'front-passage',
      front: 'Most reliable sign of **frontal passage** from the cockpit or the surface obs?',
      back: 'Wind shift (and a temperature change; pressure falls then rises).',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'ts-ingredients',
      front: 'Three ingredients of a **thunderstorm**?',
      back: 'Moisture, unstable air, and a lifting force.',
      cite: 'PHAK Ch. 12; AC 00-6',
    },
    {
      slug: 'ts-stages',
      front: 'The three thunderstorm **stages** and each one’s signature?',
      back: 'Cumulus: updrafts building. Mature: precipitation begins — updrafts AND downdrafts, the most violent period. Dissipating: downdrafts dominate.',
      why: 'Rain starting at the surface marks the mature stage — the worst time to be anywhere near it.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'ts-avoid',
      front: 'How far do you stay from a **severe** thunderstorm?',
      back: 'At least 20 NM — hail and severe turbulence live in clear air beside and beneath the anvil.',
      cite: 'AIM 7-1-27',
    },
    {
      slug: 'microburst',
      front: 'A **microburst**: size, life, worst-case wind change?',
      back: 'Small (<1 NM per FAA guidance) intense downdraft, ~15 min life, downdrafts to 6,000 fpm and headwind-to-tailwind shear of 45+ knots.',
      why: 'The killer sequence on approach: rising performance (headwind), then a floor drops out (downdraft), then a tailwind you can’t out-climb. Go around at the FIRST sign.',
      cite: 'AIM 7-1-24',
    },
    {
      slug: 'icing-required',
      front: 'Two conditions required for structural **icing**?',
      back: 'Visible moisture (cloud, rain) and surface/air temperature at or below freezing.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'icing-types',
      front: '**Clear** vs **rime** ice — formation and danger?',
      back: 'Clear: large supercooled drops (freezing rain/cumuliform) spreading before freezing — heavy, hard, hard to see, worst kind. Rime: small drops freezing instantly — rough, milky, brittle, disrupts airflow.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'freezing-rain',
      front: 'You hit **freezing rain**. What does it tell you about the air above?',
      back: 'Warmer air (above freezing) exists ABOVE you — rain formed there and is supercooling as it falls into your colder layer.',
      why: 'Classic escape is a climb to the warm layer — but for a VFR private pilot the real answer is a 180 and land. Fastest ice accumulation there is.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'frost',
      front: 'Why is a little **frost** on the wing a big deal?',
      back: 'It disrupts the boundary layer, raising stall speed and cutting lift up to ~30% — the wing can fail to fly at normal rotation speed. Remove ALL of it.',
      cite: 'PHAK Ch. 12; AC 135-17',
      unverified: true,
    },
    {
      slug: 'mtn-wave',
      front: 'Wind across a ridge — what clouds warn of **mountain wave**?',
      back: 'Lenticular (standing lens) clouds over/downwind of peaks, rotor clouds beneath — expect strong up/downdrafts and severe turbulence.',
      why: 'The Cascades generate textbook wave. Cross ridges at a 45° angle with escape room, and add altitude margin.',
      cite: 'PHAK Ch. 12; AIM 7-6-6',
    },
    {
      slug: 'wind-shear',
      front: 'Where does low-level **wind shear** hide?',
      back: 'Near thunderstorms, frontal zones, temperature inversions with strong winds above, and terrain/obstruction wind. It can strike at any altitude, any direction.',
      cite: 'PHAK Ch. 12; AIM 7-1-24',
    },
    {
      slug: 'sea-breeze',
      front: '**Sea breeze** — direction and when?',
      back: 'From the water toward land, on warm afternoons (land heats faster). Reverses at night (land breeze, toward the water).',
      why: 'Afternoon westerly filling in off the Sound is this.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'wind-friction',
      front: 'Why does surface wind differ from winds-aloft direction?',
      back: 'Surface friction slows the wind, weakening the Coriolis effect — surface wind shifts toward lower pressure (roughly 20–40° from the gradient wind) and slows.',
      why: 'Practical: expect the wind to veer and strengthen as you climb out.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'pressure-systems',
      front: 'Circulation around **highs** and **lows** (northern hemisphere)?',
      back: 'High: clockwise, outward, descending air — generally good weather. Low: counterclockwise, inward, rising air — clouds and precip.',
      why: 'Flying toward a low: expect deteriorating weather and a left crosswind correction going in.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'dew-frost-form',
      front: 'Frost forms by what process?',
      back: 'Deposition — water vapor turning directly to ice on a surface at or below freezing (dewpoint also below freezing).',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'turb-types',
      front: 'Turbulence reporting scale — what makes it “moderate” vs “severe”?',
      back: 'Moderate: changes in altitude/attitude, positive control remains, occupants strain against belts. Severe: large abrupt changes, aircraft may be momentarily out of control.',
      cite: 'AIM 7-1-21',
    },
    {
      slug: 'virga',
      front: 'What is **virga**, and the hazard beneath it?',
      back: 'Precipitation evaporating before reaching the ground — evaporative cooling can drive strong downdrafts and low-level wind shear below.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'rain-shadow',
      front: 'Why is Sequim dry while Forks drowns — and what does that do to your flying weather?',
      back: 'Orographic lift: Pacific air rises over the Olympics and Cascades, wringing out rain on the windward side; the lee side sits in a rain shadow. Windward slopes = clouds, ice, and obscured terrain; lee side = clearer but turbulent.',
      why: 'The same mechanism hides the passes in cloud while both valleys report VFR. Pass webcams before mountain flights.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'tcu-cb',
      front: 'A METAR appends **TCU** vs **CB** to a cloud layer — difference?',
      back: 'TCU: towering cumulus — strong convection building. CB: cumulonimbus — a thunderstorm, present or imminent. Both mean turbulence; CB means everything else too.',
      cite: 'AC 00-45',
    },
    {
      slug: 'cloud-families',
      front: 'The four cloud families by altitude, and the dangerous cross-family one?',
      back: 'High (cirro-), middle (alto-), low (stratus/cumulus), and clouds of vertical development (cumulonimbus spans all levels). Nimbo/nimbus = rain-bearing.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'winds-aloft',
      front: 'Decode a winds-aloft (FB) entry: `2418+05` — and the special code `9900`?',
      back: 'Wind 240° true at 18 kt, temp +5°C. `9900` = light and variable (under 5 kt).',
      why: 'Above 24,000 ft the temp sign is omitted (always negative). Winds >99 kt add 50 to the direction digits.',
      cite: 'AC 00-45',
    },
    {
      slug: 'icing-pirep-scale',
      front: 'PIREP icing intensities, in order?',
      back: 'Trace, light, moderate, severe. “Severe” means deice/anti-ice can’t keep up — an immediate-diversion word.',
      cite: 'AIM 7-1-20',
    },
    {
      slug: 'graphical-products',
      front: 'Where do you get a visual overview briefing these days?',
      back: 'The Graphical Forecasts for Aviation (GFA) on aviationweather.gov — clouds, ceilings, precip, winds by the hour; plus prog charts for the synoptic picture. (The old text area forecast is retired.)',
      cite: 'AC 00-45; aviationweather.gov',
    },
    {
      slug: 'sigmet-names',
      front: 'How are SIGMETs and AIRMETs identified, and how long do they run?',
      back: 'SIGMETs: lettered series (November, Oscar…), valid up to 4 hrs. AIRMETs: Sierra/Tango/Zulu, 6-hr periods. Convective SIGMETs: hourly, valid 2 hrs.',
      cite: 'AIM 7-1-6',
      unverified: true,
    },
    {
      slug: 'front-cross-section',
      front: 'Flying WEST toward an approaching **warm front** — what sequence of clouds greets you?',
      back: 'Cirrus first (hundreds of miles out), then cirrostratus, altostratus, nimbostratus with steady rain and falling ceilings as you near the surface front.',
      why: 'The high thin harbingers a day ahead are the front introducing itself.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'squall-line',
      front: 'What is a **squall line**, and why is it worse than the cold front that spawned it?',
      back: 'A solid band of severe thunderstorms, often 50–300 NM ahead of a fast cold front — frequently too long to go around and far too violent to penetrate.',
      cite: 'PHAK Ch. 12',
    },
    {
      slug: 'hail-where',
      front: 'Where can hail ambush you near a thunderstorm?',
      back: 'In CLEAR AIR beneath and downwind of the anvil — miles from the rain shaft. Another reason for the 20 NM rule.',
      cite: 'PHAK Ch. 12; AIM 7-1-27',
    },
    {
      slug: 'briefing-types',
      front: 'The three FSS briefing types and when each fits?',
      back: 'Standard: full brief for a planned flight. Abbreviated: update specific items of an earlier brief. Outlook: departure 6+ hours away, planning purposes.',
      cite: 'AIM 7-1-5',
    },
    {
      slug: 'notam-types',
      front: 'NOTAM flavors you’ll actually meet?',
      back: 'NOTAM (D): distant — airport/navaid status. FDC: regulatory — TFRs, chart/procedure changes. Both are mandatory preflight reading under 91.103.',
      cite: 'AIM 5-1-3; 14 CFR 91.103',
    },
  ],
);
