import { qbank } from './types';

/* Regulations, airspace, and radio/procedures questions. */

export const regsQuestions = qbank('xr', 'regs', [
  {
    slug: 'fuel-night',
    q: 'What is the minimum fuel reserve for a VFR flight at night?',
    choices: [
      'Enough to fly to the first point of intended landing plus 30 minutes at normal cruise',
      'Enough to fly to the first point of intended landing plus 45 minutes at normal cruise',
      'Enough to fly to the first point of intended landing plus 1 hour at normal cruise',
    ],
    answer: 1,
    why: 'Day VFR requires 30 minutes reserve; night VFR requires 45 minutes, both computed at normal cruising speed.',
    cite: '14 CFR 91.151',
  },
  {
    slug: 'flight-review',
    q: 'To act as pilot in command, a pilot must have completed a flight review (or equivalent) within the preceding —',
    choices: ['12 calendar months', '24 calendar months', '6 calendar months'],
    answer: 1,
    why: 'The flight review is required every 24 calendar months: at least 1 hour of flight training and 1 hour of ground training. A new certificate or rating also counts.',
    cite: '14 CFR 61.56',
  },
  {
    slug: 'pax-currency',
    q: 'To carry passengers, a pilot must have made within the preceding 90 days —',
    choices: [
      'three takeoffs and landings in any aircraft',
      'three takeoffs and landings as sole manipulator in an aircraft of the same category and class',
      'one takeoff and landing in the same category and class',
    ],
    answer: 1,
    why: 'Three takeoffs and landings in the preceding 90 days, as sole manipulator of the controls, in the same category/class (and type, if a type rating is required). At night they must be to a full stop.',
    cite: '14 CFR 61.57',
  },
  {
    slug: 'medical-under40',
    q: 'A third-class medical certificate was issued to a 25-year-old pilot on May 3 of this year. It expires —',
    choices: [
      'at the end of May, 24 calendar months later',
      'at the end of May, 60 calendar months later',
      'on May 3, 60 months later',
    ],
    answer: 1,
    why: 'Under 40 at the time of the exam: a third-class medical is valid for 60 calendar months — through the last day of that month.',
    cite: '14 CFR 61.23',
  },
  {
    slug: 'alcohol-8hr',
    q: 'A pilot may not act as a crewmember within what time after consuming alcohol, and above what blood alcohol level?',
    choices: [
      '8 hours, and 0.04% BAC',
      '12 hours, and 0.04% BAC',
      '8 hours, and 0.08% BAC',
    ],
    answer: 0,
    why: '“Eight hours bottle to throttle,” no acting as crew while under the influence, and never at or above 0.04% BAC.',
    cite: '14 CFR 91.17',
  },
  {
    slug: 'row-converge',
    q: 'Two airplanes are converging at the same altitude (not head-on). Which has the right-of-way?',
    choices: [
      'The aircraft on the left',
      'The aircraft on the right',
      'The faster aircraft',
    ],
    answer: 1,
    why: 'When aircraft of the same category converge, the aircraft to the other’s right has the right-of-way.',
    cite: '14 CFR 91.113(d)',
  },
  {
    slug: 'row-balloon',
    q: 'An airplane and a balloon are converging. Who must give way?',
    choices: ['The balloon', 'The airplane', 'Whichever is lower'],
    answer: 1,
    why: 'The less maneuverable aircraft has the right-of-way: balloons beat gliders, which beat airships, which beat airplanes and rotorcraft.',
    cite: '14 CFR 91.113',
  },
  {
    slug: 'min-alt-congested',
    q: 'Over a congested area, the minimum altitude is —',
    choices: [
      '500 ft above the surface',
      '1,000 ft above the highest obstacle within a 2,000-ft horizontal radius',
      '2,000 ft above the highest obstacle within a 1,000-ft horizontal radius',
    ],
    answer: 1,
    why: 'Congested areas: 1,000 ft above the highest obstacle within 2,000 ft horizontally. Elsewhere: 500 ft above the surface (or 500 ft from persons/structures in sparse areas).',
    cite: '14 CFR 91.119',
  },
  {
    slug: 'vfr-cruise',
    q: 'Flying VFR at more than 3,000 ft AGL on a magnetic course of 135°, an appropriate cruising altitude is —',
    choices: ['4,500 ft MSL', '5,500 ft MSL', '6,000 ft MSL'],
    answer: 1,
    why: 'Magnetic course 0–179°: odd thousands plus 500 ft (3,500, 5,500, 7,500…). 135° is in the odd+500 hemisphere.',
    cite: '14 CFR 91.159',
  },
  {
    slug: 'oxygen',
    q: 'Flight crew must use supplemental oxygen after 30 minutes above a cabin pressure altitude of —',
    choices: ['10,000 ft MSL', '12,500 ft MSL', '14,000 ft MSL'],
    answer: 1,
    why: 'Above 12,500 up to 14,000: required beyond 30 minutes. Above 14,000: crew required at all times. Above 15,000: passengers must be provided oxygen.',
    cite: '14 CFR 91.211',
  },
  {
    slug: 'arrow',
    q: 'Which documents must be aboard the aircraft for flight?',
    choices: [
      'Airworthiness certificate, registration, operating limitations, weight & balance data',
      'Logbooks, airworthiness certificate, registration',
      'POH, insurance documents, annual inspection report',
    ],
    answer: 0,
    why: 'ARROW: Airworthiness, Registration, Radio license (international only), Operating limitations, Weight & balance. Maintenance logbooks stay on the ground.',
    cite: '14 CFR 91.203, 91.9',
  },
  {
    slug: 'private-comp',
    q: 'A private pilot flies friends to a concert and they split costs. The pilot must pay at least —',
    choices: [
      'nothing, as agreed among friends',
      'an equal (pro-rata) share of the operating expenses',
      'the fuel only',
    ],
    answer: 1,
    why: 'A private pilot may not pay less than a pro-rata share of operating expenses (fuel, oil, airport fees, rental) shared with passengers — and there must be a common purpose.',
    cite: '14 CFR 61.113(c)',
  },
  {
    slug: 'inop-instrument',
    q: 'The clock in your day-VFR trainer fails before flight. Under 91.213(d) (no MEL), you may fly if —',
    choices: [
      'a mechanic ferries the airplane',
      'it is not required equipment, and it is deactivated or removed and placarded INOPERATIVE',
      'the flight remains within 50 NM',
    ],
    answer: 1,
    why: 'Non-required inoperative equipment must be removed or deactivated AND placarded, and the PIC must determine the aircraft is safe for the flight.',
    cite: '14 CFR 91.213(d)',
  },
  {
    slug: 'annual-expired',
    q: 'The annual inspection expired yesterday. You may —',
    choices: [
      'fly locally within 25 NM',
      'not fly, except with a special flight permit (ferry permit) to a place where the inspection can be done',
      'fly for up to 10 additional flight hours',
    ],
    answer: 1,
    why: 'No annual, no flying — the 10-hour allowance applies only to the 100-hour inspection, and only to REACH the inspection facility.',
    cite: '14 CFR 91.409; 21.197',
  },
  {
    slug: 'ntsb-immediate',
    q: 'Which event requires IMMEDIATE notification to the NTSB?',
    choices: [
      'A hard landing that scrapes a wingtip fairing',
      'In-flight failure of a flight control system',
      'A blown tire on landing',
    ],
    answer: 1,
    why: 'Flight control system malfunction/failure is on the 830.5 immediate-notification list, along with crew incapacitation, in-flight fire, mid-air collision, and others.',
    cite: '49 CFR 830.5',
  },
  {
    slug: 'preventive-maint',
    q: 'Which task may a private pilot legally perform on an aircraft they operate?',
    choices: [
      'Replacing a magneto',
      'Changing the engine oil and servicing the battery',
      'Adjusting the flight control cable tension',
    ],
    answer: 1,
    why: 'Preventive maintenance (Part 43 Appendix A(c)) covers items like oil changes, bulb/spark plug replacement, tire changes — with a proper log entry. Magnetos and control rigging are not on the list.',
    cite: '14 CFR 43.3(g)',
  },
]);

export const airspaceQuestions = qbank('xa', 'airspace', [
  {
    slug: 'b-entry',
    q: 'Before entering Class B airspace, a pilot must —',
    choices: [
      'establish two-way radio communications',
      'receive an explicit ATC clearance into the Class B',
      'file a VFR flight plan',
    ],
    answer: 1,
    why: 'Class B is the one airspace where hearing your callsign is not enough — you must hear “cleared into the Class Bravo airspace.”',
    cite: '14 CFR 91.131',
  },
  {
    slug: 'c-entry',
    q: 'You call “Approach, Skyhawk 731TW, 10 east with Bravo” and hear “Skyhawk 731TW, standby.” May you enter the Class C?',
    choices: [
      'No — “standby” always denies entry',
      'Yes — two-way communications are established because ATC used your callsign',
      'Only after receiving a discrete squawk code',
    ],
    answer: 1,
    why: 'Communications are established once ATC responds with your callsign — even “standby.” If they say “aircraft calling, standby,” communications are NOT established.',
    cite: 'AIM 3-2-4; 14 CFR 91.130',
  },
  {
    slug: 'd-dims',
    q: 'Class D airspace typically extends from the surface to —',
    choices: [
      '2,500 ft above the airport elevation',
      '4,000 ft above the airport elevation',
      '10,000 ft MSL',
    ],
    answer: 0,
    why: 'Class D normally runs surface to 2,500 ft above airport elevation, charted in MSL in the dashed box.',
    cite: 'AIM 3-2-5',
  },
  {
    slug: 'e-vfr-high',
    q: 'VFR minimums in Class E at 11,500 ft MSL are —',
    choices: [
      '3 SM; 500 below, 1,000 above, 2,000 horizontal',
      '5 SM; 1,000 below, 1,000 above, 1 SM horizontal',
      '5 SM; clear of clouds',
    ],
    answer: 1,
    why: 'At or above 10,000 MSL in Class E (and G): 5 SM and 1,000/1,000/1 SM — faster traffic, more room required.',
    cite: '14 CFR 91.155',
  },
  {
    slug: 'g-day',
    q: 'Day VFR minimums in Class G at 800 ft AGL are —',
    choices: [
      '1 SM, clear of clouds',
      '3 SM; 500/1,000/2,000',
      '1 SM; 500/1,000/2,000',
    ],
    answer: 0,
    why: 'Class G at or below 1,200 AGL, day: 1 statute mile and clear of clouds.',
    cite: '14 CFR 91.155',
  },
  {
    slug: 'b-vfr',
    q: 'VFR cloud clearance inside Class B airspace is —',
    choices: [
      '500 below, 1,000 above, 2,000 horizontal',
      'clear of clouds',
      '1,000 above and below, 1 SM horizontal',
    ],
    answer: 1,
    why: 'Class B: 3 SM visibility and clear of clouds — ATC is separating all traffic, so only cloud avoidance is on you.',
    cite: '14 CFR 91.155',
  },
  {
    slug: 'modec-veil',
    q: 'A Mode C transponder and ADS-B Out are required within what radius of a Class B primary airport?',
    choices: ['20 NM', '30 NM', '10 NM'],
    answer: 1,
    why: 'The Mode C veil is 30 NM — it applies from the surface up to 10,000 MSL, even outside the Bravo’s lateral limits.',
    cite: '14 CFR 91.215, 91.225',
  },
  {
    slug: 'moa-vfr',
    q: 'May a VFR flight enter an active MOA without a clearance?',
    choices: [
      'No, a clearance is required',
      'Yes, but with extreme caution for military traffic',
      'Only on weekends',
    ],
    answer: 1,
    why: 'MOAs don’t restrict VFR — but active military maneuvering makes checking status with ATC/FSS and heads-up flying essential.',
    cite: 'AIM 3-4-5',
  },
  {
    slug: 'restricted',
    q: 'Flight through an active restricted area requires —',
    choices: [
      'permission from the using or controlling agency',
      'only two-way radio contact',
      'nothing — restricted areas are advisory',
    ],
    answer: 0,
    why: 'Restricted areas contain hazards like artillery and gunnery. Entry when active requires authorization; when inactive, ATC may clear you through.',
    cite: '14 CFR 73; AIM 3-4-3',
  },
  {
    slug: 'speed-under-b',
    q: 'The maximum indicated airspeed beneath a Class B shelf is —',
    choices: ['250 knots', '230 knots', '200 knots'],
    answer: 2,
    why: '200 KIAS under Bravo shelves and in VFR corridors; 250 below 10,000 MSL generally; 200 at/below 2,500 AGL within 4 NM of a C/D primary.',
    cite: '14 CFR 91.117',
  },
]);

export const radioQuestions = qbank('xc', 'radio', [
  {
    slug: 'holdshort',
    q: '“Skyhawk 1TW, Runway 17, taxi via Alpha, hold short Runway 35.” The required response is —',
    choices: [
      '“Roger, Skyhawk 1TW”',
      '“Runway 17 via Alpha, hold short Runway 35, Skyhawk 1TW”',
      'Two clicks of the mic',
    ],
    answer: 1,
    why: 'Hold-short instructions must be read back verbatim with your callsign. “Roger” is never acceptable for a hold-short.',
    cite: 'AIM 4-3-18',
  },
  {
    slug: 'luaw',
    q: '“Line up and wait” authorizes you to —',
    choices: [
      'taxi onto the runway and stop — takeoff clearance comes separately',
      'take off when traffic permits',
      'hold short of the runway',
    ],
    answer: 0,
    why: 'Position yourself on the runway and wait. Takeoff requires the explicit words “cleared for takeoff.”',
    cite: 'P/CG; AIM 5-2-5',
  },
  {
    slug: 'lightgun-red-flight',
    q: 'In flight, a steady red light from the tower means —',
    choices: [
      'airport unsafe, do not land',
      'give way to other aircraft and continue circling',
      'cleared to land',
    ],
    answer: 1,
    why: 'Steady red in flight: give way and continue circling. Flashing red is “airport unsafe — do not land.”',
    cite: 'AIM 4-3-13; 14 CFR 91.125',
  },
  {
    slug: 'nordo-code',
    q: 'Your radio fails in flight. You should squawk —',
    choices: ['7500', '7600', '7700'],
    answer: 1,
    why: '7500 hijack, 7600 communications failure, 7700 emergency. “75 taken alive, 76 radio fix, 77 going to heaven.”',
    cite: 'AIM 6-4-2',
  },
  {
    slug: 'ctaf',
    q: 'The recommended self-announce position report at a non-towered airport begins and ends with —',
    choices: [
      'your callsign',
      'the airport name',
      '“traffic in the area please advise”',
    ],
    answer: 1,
    why: '“Bremerton traffic, Skyhawk 731TW, left downwind Runway 20, Bremerton.” Several airports share frequencies; the name bounds the call. “Please advise” is specifically discouraged.',
    cite: 'AIM 4-1-9',
  },
]);

export const proceduresQuestions = qbank('xp', 'procedures', [
  {
    slug: 'pattern-turns',
    q: 'Unless otherwise indicated, all turns in the traffic pattern at a non-towered airport are made —',
    choices: ['to the left', 'to the right', 'toward the wind'],
    answer: 0,
    why: 'Left traffic is standard. Right patterns are marked by the segmented circle, “RP” on the sectional, and the Chart Supplement.',
    cite: '14 CFR 91.126',
  },
  {
    slug: 'displaced',
    q: 'A displaced threshold may be used for —',
    choices: [
      'takeoff only',
      'taxi, takeoff, and landing rollout — but not touchdown',
      'no operations',
    ],
    answer: 1,
    why: 'The paved area before a displaced threshold supports taxi, takeoff, and rollout. Touch down beyond the threshold bar. Chevrons, by contrast, are unusable entirely.',
    cite: 'AIM 2-3-3',
  },
  {
    slug: 'wake-landing',
    q: 'Landing behind a departing large jet on the same runway, you should plan to —',
    choices: [
      'land before its rotation point',
      'land beyond its rotation point',
      'fly a lower-than-normal approach',
    ],
    answer: 0,
    why: 'A departing jet’s vortices begin at rotation. Land well BEFORE its rotation point. (Landing behind a LANDING jet: land beyond its touchdown point.)',
    cite: 'AIM 7-4 (wake turbulence)',
    unverified: true,
  },
  {
    slug: 'beacon-day',
    q: 'An airport beacon operating during daylight hours may indicate —',
    choices: [
      'the airport is closed',
      'weather below basic VFR minimums (ceiling <1,000 ft or visibility <3 SM) in the surface area',
      'parachute operations in progress',
    ],
    answer: 1,
    why: 'A daytime beacon in Class B/C/D/E surface areas often means ground visibility under 3 miles and/or ceiling under 1,000 — but there is no regulatory requirement, so verify with the ATIS/METAR.',
    cite: 'AIM 2-1-9',
  },
  {
    slug: 'lahso',
    q: 'Tower offers “cleared to land Runway 17, hold short of Runway 26.” As a student or new pilot you should —',
    choices: [
      'accept — LAHSO clearances are mandatory',
      'decline if unable, and student pilots should not participate in LAHSO',
      'accept and decide on rollout',
    ],
    answer: 1,
    why: 'The PIC may always decline LAHSO. Accepting requires knowing the available landing distance and being sure you can stop; student pilots should not accept.',
    cite: 'AIM 4-3-11',
  },
  {
    slug: 'engine-out-glide',
    q: 'The engine fails at cruise altitude. Your FIRST action should be —',
    choices: [
      'establish best glide speed',
      'squawk 7700 and call Mayday',
      'attempt an engine restart',
    ],
    answer: 0,
    why: 'Fly the airplane first: pitch/trim for best glide preserves your options. Then field, then checklist/restart, then declare. Aviate, navigate, communicate.',
    cite: 'AFH Ch. 17',
  },
  {
    slug: 'taxi-quartering-tail',
    q: 'Taxiing with a quartering tailwind from the left rear, position the controls —',
    choices: [
      'left aileron up, elevator neutral',
      'left aileron down, elevator down',
      'right aileron up, elevator up',
    ],
    answer: 1,
    why: 'Tailwind: “dive away from the wind” — stick forward (elevator down) and aileron away from the wind, i.e., the wind-side aileron down.',
    cite: 'AFH Ch. 2',
  },
  {
    slug: 'vasi-two-red',
    q: 'On a PAPI you see two white and two red lights. You are —',
    choices: ['slightly high', 'on the glidepath', 'slightly low'],
    answer: 1,
    why: 'PAPI: 4W high, 3W1R slightly high, 2W2R on path, 1W3R slightly low, 4R too low.',
    cite: 'AIM 2-1-2',
  },
]);
