import { qbank } from './types';

/* Weather, charts, aerodynamics questions. */

export const weatherQuestions = qbank('xw', 'weather', [
  {
    slug: 'ceiling',
    q: 'METAR: `FEW008 SCT015 BKN025 OVC040`. The ceiling is —',
    choices: ['800 ft', '2,500 ft', '1,500 ft'],
    answer: 1,
    why: 'Ceiling is the lowest BROKEN or OVERCAST layer — BKN025 = 2,500 ft AGL. Few and scattered don’t count.',
    cite: 'P/CG “CEILING”',
  },
  {
    slug: 'wind-true-mag',
    q: 'The wind direction in a written METAR is referenced to —',
    choices: ['magnetic north', 'true north', 'the runway heading'],
    answer: 1,
    why: 'Written products (METAR/TAF/winds aloft) are TRUE; spoken winds from tower/ATIS are MAGNETIC — so they line up with runway numbers.',
    cite: 'AC 00-45',
  },
  {
    slug: 'cat-example',
    q: 'METAR reports `OVC009` and 4 SM. The flight category is —',
    choices: ['MVFR', 'IFR', 'LIFR'],
    answer: 1,
    why: 'Ceiling 900 ft is below 1,000 → IFR (500–999 and/or 1–3 SM). The worse of ceiling or visibility sets the category.',
    cite: 'AC 00-45',
  },
  {
    slug: 'fg-vis',
    q: 'For fog (`FG`) to be reported rather than mist (`BR`), visibility must be —',
    choices: ['less than 5/8 SM', 'less than 3 SM', 'less than 1 SM'],
    answer: 0,
    why: 'FG: visibility below 5/8 SM. BR (mist): 5/8 SM to 6 SM.',
    cite: 'AC 00-45',
  },
  {
    slug: 'ts-stage',
    q: 'The beginning of surface rain at an airport beneath a building cumulus signals which thunderstorm stage?',
    choices: ['Cumulus', 'Mature', 'Dissipating'],
    answer: 1,
    why: 'Precipitation reaching the surface marks the mature stage — updrafts and downdrafts coexist and the storm is at maximum intensity.',
    cite: 'PHAK Ch. 12',
  },
  {
    slug: 'radiation-fog',
    q: 'Conditions most favorable for radiation fog are —',
    choices: [
      'warm moist air moving over a cold surface',
      'clear skies, light wind, and moist air over land at night',
      'strong winds and steep terrain',
    ],
    answer: 1,
    why: 'Radiation fog forms as land cools under clear, calm nights. Warm-air-over-cold-surface is ADVECTION fog (the coastal kind).',
    cite: 'PHAK Ch. 12',
  },
  {
    slug: 'stable-air',
    q: 'Flying in smooth air with steady rain, stratus clouds, and poor visibility indicates —',
    choices: ['unstable air', 'stable air', 'an approaching cold front'],
    answer: 1,
    why: 'Stable air: stratiform clouds, continuous precipitation, smooth ride, poor visibility. Unstable: cumuliform, showers, turbulence, good visibility.',
    cite: 'PHAK Ch. 12',
  },
  {
    slug: 'freezing-rain',
    q: 'Encountering freezing rain tells you that at some higher altitude the temperature is —',
    choices: ['colder than at your altitude', 'above freezing', 'exactly 0°C'],
    answer: 1,
    why: 'Rain must have formed (or melted) in above-freezing air aloft, then supercooled falling into your sub-freezing layer. Fastest structural icing there is.',
    cite: 'PHAK Ch. 12',
  },
  {
    slug: 'ts-ingredients',
    q: 'For a thunderstorm to form, the atmosphere needs moisture, lifting action, and —',
    choices: ['a temperature inversion', 'unstable air', 'high pressure'],
    answer: 1,
    why: 'Moisture + instability + lift. An inversion is the opposite: it caps convection.',
    cite: 'PHAK Ch. 12',
  },
  {
    slug: 'lenticular',
    q: 'Standing lenticular clouds over the Cascades indicate —',
    choices: [
      'stable, smooth flying conditions near the ridge',
      'strong mountain wave activity with possible severe turbulence',
      'imminent thunderstorms',
    ],
    answer: 1,
    why: 'Lenticulars mark strong standing waves. The clouds are smooth-looking; the air (especially in rotors below) is anything but.',
    cite: 'PHAK Ch. 12',
    unverified: true,
  },
  {
    slug: 'airmet-zulu',
    q: 'AIRMET Zulu warns of —',
    choices: ['moderate icing', 'moderate turbulence', 'IFR conditions'],
    answer: 0,
    why: 'Zulu = icing and freezing level. Tango = turbulence/winds. Sierra = IFR conditions and mountain obscuration.',
    cite: 'AIM 7-1-6',
  },
  {
    slug: 'dewpoint-close',
    q: 'A METAR shows temperature 12°C, dewpoint 11°C, with clear skies at sunset. Expect —',
    choices: [
      'improving visibility overnight',
      'fog or low stratus forming',
      'thunderstorm development',
    ],
    answer: 1,
    why: 'A 1° spread with nighttime cooling ahead is a fog recipe — the air saturates as temperature falls to the dewpoint.',
    cite: 'PHAK Ch. 12',
  },
]);

export const chartsQuestions = qbank('xh', 'charts', [
  {
    slug: 'magenta-apt',
    q: 'An airport symbol printed in magenta on a sectional indicates —',
    choices: ['a private airport', 'an airport without a control tower', 'a seaplane base'],
    answer: 1,
    why: 'Magenta = non-towered; blue = towered.',
    cite: 'FAA Chart Users’ Guide',
  },
  {
    slug: 'mef',
    q: 'The quadrangle figure 3⁴ on a sectional (MEF) represents —',
    choices: [
      'a safe altitude guaranteeing obstacle clearance',
      'the highest terrain or obstruction in the quadrangle, 3,400 ft MSL, rounded up',
      'minimum enroute IFR altitude',
    ],
    answer: 1,
    why: 'Maximum Elevation Figure: highest feature rounded UP to the next 100 ft. It includes no buffer for you — add your own margin.',
    cite: 'FAA Chart Users’ Guide',
  },
  {
    slug: 'dashed-magenta',
    q: 'A dashed magenta line around an airport indicates —',
    choices: [
      'Class D airspace',
      'Class E airspace extending to the surface',
      'a military operations area',
    ],
    answer: 1,
    why: 'Dashed magenta = surface Class E (protecting instrument approaches). Dashed blue = Class D.',
    cite: 'FAA Chart Users’ Guide',
  },
  {
    slug: 'vignette',
    q: 'Inside the fuzzy magenta vignette, Class E airspace begins at —',
    choices: ['the surface', '700 ft AGL', '1,200 ft AGL'],
    answer: 1,
    why: 'Magenta vignette: E starts at 700 AGL inside; 1,200 AGL outside. Below that floor you’re in Class G.',
    cite: 'FAA Chart Users’ Guide; AIM 3-2-6',
  },
  {
    slug: 'obstruction',
    q: 'An obstruction charted as `1549 (405)` means —',
    choices: [
      'top at 1,549 ft MSL, 405 ft above the ground',
      'top at 1,549 ft AGL, ground elevation 405 ft',
      'a lit tower 1,549 ft tall',
    ],
    answer: 0,
    why: 'Bold number = MSL height of the top; parenthetical = AGL height.',
    cite: 'FAA Chart Users’ Guide',
  },
  {
    slug: 'ticks',
    q: 'Tick marks projecting from an airport circle indicate —',
    choices: [
      'runway lighting available',
      'fuel available at an attended field',
      'a rotating beacon',
    ],
    answer: 1,
    why: 'Ticks = services/fuel during normal hours. The star on top = rotating beacon.',
    cite: 'FAA Chart Users’ Guide',
  },
  {
    slug: 'd-ceiling-box',
    q: 'The number [31] in a dashed box inside a dashed blue circle means —',
    choices: [
      'Class D ceiling 3,100 ft MSL',
      'CTAF frequency 131.0',
      'field elevation 310 ft',
    ],
    answer: 0,
    why: 'Class D ceiling in hundreds of feet MSL. A minus prefix means “up to but not including.”',
    cite: 'FAA Chart Users’ Guide',
  },
  {
    slug: 'isogonic',
    q: 'True course 090°, variation 15°E. Magnetic course is —',
    choices: ['105°', '075°', '090°'],
    answer: 1,
    why: '“East is least”: subtract easterly variation. 090 − 15 = 075 magnetic. (West variation would be added.)',
    cite: 'PHAK Ch. 16',
  },
]);

export const aeroQuestions = qbank('xd', 'aero', [
  {
    slug: 'stall-any',
    q: 'An airplane stalls whenever —',
    choices: [
      'airspeed falls below published stall speed',
      'the critical angle of attack is exceeded',
      'power is reduced below minimum',
    ],
    answer: 1,
    why: 'Critical AOA is the only cause — at any airspeed, attitude, or power setting. Published stall speeds assume 1g and specified configuration.',
    cite: 'PHAK Ch. 5',
  },
  {
    slug: 'load-60',
    q: 'In a level, coordinated 60° bank turn, the load factor is —',
    choices: ['1.4 g', '2.0 g', '3.0 g'],
    answer: 1,
    why: '60° of bank in level flight doubles the load on the wings regardless of aircraft type — and raises stall speed about 41%.',
    cite: 'PHAK Ch. 5',
  },
  {
    slug: 'va-weight',
    q: 'As aircraft weight decreases, maneuvering speed (Va) —',
    choices: ['increases', 'decreases', 'is unchanged'],
    answer: 1,
    why: 'Lighter = flying at lower AOA = more margin below critical AOA = the gust/pull can generate more g before stalling. So Va is LOWER when light.',
    cite: 'PHAK Ch. 5',
  },
  {
    slug: 'ground-effect-to',
    q: 'A hazard of ground effect on takeoff is that the airplane may —',
    choices: [
      'be unable to lift off',
      'lift off before reaching a speed that can sustain climb out of ground effect',
      'experience increased induced drag near the surface',
    ],
    answer: 1,
    why: 'Within a wingspan of the ground, reduced induced drag lets the plane fly early — then settle back or mush when it climbs out of the cushion.',
    cite: 'PHAK Ch. 5',
  },
  {
    slug: 'p-factor-when',
    q: 'P-factor causes a left-yawing tendency that is greatest at —',
    choices: [
      'high airspeed, low angle of attack',
      'low airspeed, high angle of attack, high power',
      'idle power in a descent',
    ],
    answer: 1,
    why: 'The descending blade’s bigger bite matters most at high AOA and high power — climbout, short-field takeoffs, slow flight.',
    cite: 'PHAK Ch. 5',
  },
  {
    slug: 'spin-requirement',
    q: 'A spin can occur only if the airplane is —',
    choices: ['in a steep bank', 'stalled', 'at forward CG'],
    answer: 1,
    why: 'Spin = stall + yaw. No stall, no spin. Keeping the ball centered near the stall is the protection.',
    cite: 'PHAK Ch. 5; AFH',
  },
  {
    slug: 'aft-cg',
    q: 'Loading at or beyond the aft CG limit makes the airplane —',
    choices: [
      'more stable with heavier stick forces',
      'less stable, with potentially impossible stall/spin recovery',
      'nose-heavy in the flare',
    ],
    answer: 1,
    why: 'Aft CG reduces the tail’s restoring moment: light pitch forces, weak nose-drop at the stall, and spins may go flat.',
    cite: 'PHAK Ch. 5, 10',
  },
  {
    slug: 'adverse-yaw',
    q: 'Rolling into a left turn, the nose initially yaws right because —',
    choices: [
      'of torque from the engine',
      'the rising wing’s aileron creates more induced drag',
      'the rudder is misrigged',
    ],
    answer: 1,
    why: 'Adverse yaw: the down-deflected aileron on the rising (right) wing makes extra lift AND extra induced drag, pulling the nose opposite the roll. Coordinate with rudder.',
    cite: 'PHAK Ch. 6',
  },
  {
    slug: 'vx-vy',
    q: 'To clear trees at the end of a short runway, climb at —',
    choices: ['Vy, best rate of climb', 'Vx, best angle of climb', 'cruise climb'],
    answer: 1,
    why: 'Vx gives the most altitude per unit of GROUND DISTANCE — the obstacle metric. Vy gives most altitude per unit time.',
    cite: 'PHAK Ch. 11',
  },
  {
    slug: 'frost-effect',
    q: 'Frost on the wings —',
    choices: [
      'may be polished smooth for takeoff',
      'must be removed — it disrupts airflow and can prevent takeoff',
      'only matters above 100 knots',
    ],
    answer: 1,
    why: 'Even thin frost raises stall speed and can keep a wing from flying at normal rotation speed. Remove it all.',
    cite: 'PHAK Ch. 5',
  },
]);
